// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "다시 처음으로 돌아올게요.",
    startFrame: 0,
    endFrame: 50
  },
  {
    text: "21번 중 20번 핵을 선택하고, 잘못된 판단으로\n큰 사상자를 낼 수도 있는 AI는 이제 영화 얘기가",
    startFrame: 50,
    endFrame: 289
  },
  {
    text: "아니에요. 이미 현실이에요.",
    startFrame: 289,
    endFrame: 355
  },
  {
    text: "이게 우리가 AI를 무작정 두려워하기보다,\n똑바로 알고 공부해야 하는 이유입니다.",
    startFrame: 355,
    endFrame: 548
  },
  {
    text: "나만 모르면 진짜 영화 속 엑스트라처럼 휩쓸려 갈\n수도 있으니까요.",
    startFrame: 548,
    endFrame: 703
  },
  {
    text: "오늘 제 얘기가 '아, 세상이 진짜 이렇게 돌아가고\n있구나' 하고 조금이라도 와닿으셨다면 구독 한번",
    startFrame: 731,
    endFrame: 946
  },
  {
    text: "꾹 눌러주세요. 아, 그리고 영상 끄기 전에 이거\n하나만 댓글로 남겨주세요.",
    startFrame: 946,
    endFrame: 1133
  },
  {
    text: "'내 목숨이 걸린 전쟁터, 사람 사령관을 믿을\n것인가, 냉철한 AI를 믿을 것인가?'",
    startFrame: 1133,
    endFrame: 1315
  },
];
