// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "마지막으로 처음에 말씀드린 전쟁 시뮬레이션 결과를 얘기하며",
    startFrame: 0,
    endFrame: 110
  },
  {
    text: "이야기 마치겠습니다. 올해 2월,",
    startFrame: 110,
    endFrame: 165
  },
  {
    text: "영국 킹스칼리지 런던 연구팀이 흥미로운 실험을 하나",
    startFrame: 165,
    endFrame: 288
  },
  {
    text: "진행했습니다. GPT, 클로드,",
    startFrame: 288,
    endFrame: 363
  },
  {
    text: "제미나이한테 가상의 국가 지도자 역할을 맡긴 거예요.",
    startFrame: 363,
    endFrame: 498
  },
  {
    text: "영토 분쟁, 자원 전쟁.",
    startFrame: 498,
    endFrame: 554
  },
  {
    text: "현실에서 충분히 일어날 법한 시나리오들이에요.",
    startFrame: 554,
    endFrame: 686
  },
  {
    text: "결과가 어땠냐면요. 21번 중 20번.",
    startFrame: 686,
    endFrame: 826
  },
  {
    text: "95%에서 핵무기를 선택했습니다.",
    startFrame: 826,
    endFrame: 913
  },
  {
    text: "협상도 아니고, 외교도 아니고.",
    startFrame: 913,
    endFrame: 990
  },
  {
    text: "핵 버튼이에요. 연구팀은 이렇게 말했어요.",
    startFrame: 990,
    endFrame: 1108
  },
  {
    text: "\"핵무기에 대한 금기는 인간 사회에서만큼 AI에겐 작동하지",
    startFrame: 1108,
    endFrame: 1231
  },
  {
    text: "않는다.\" 왜냐면 AI는 두렵지 않으니까요.",
    startFrame: 1231,
    endFrame: 1337
  },
  {
    text: "사람은 핵전쟁이 어떤 건지 역사로,",
    startFrame: 1337,
    endFrame: 1405
  },
  {
    text: "감정으로, 몸으로 알아요.",
    startFrame: 1405,
    endFrame: 1456
  },
  {
    text: "근데 AI한테는 그냥 \"목표 달성에 가장 효율적인 옵션\"인",
    startFrame: 1456,
    endFrame: 1560
  },
  {
    text: "거예요. 도덕적 고뇌 없이,",
    startFrame: 1560,
    endFrame: 1626
  },
  {
    text: "망설임 없이. 최적화의 결과로 핵을 선택하는 겁니다.",
    startFrame: 1626,
    endFrame: 1748
  },
  {
    text: "아까 얘기한 그 학교 기억하시나요.",
    startFrame: 1748,
    endFrame: 1820
  },
  {
    text: "168명의 아이들. AI가 점점 더 커지고,",
    startFrame: 1820,
    endFrame: 1933
  },
  {
    text: "더 많은 결정에 관여하고 있어요.",
    startFrame: 1933,
    endFrame: 1985
  },
  {
    text: "그리고 시뮬레이션에서는 핵을 선택했어요.",
    startFrame: 1985,
    endFrame: 2067
  },
  {
    text: "피한다고 피할 수 있는 게 아니에요.",
    startFrame: 2067,
    endFrame: 2128
  },
  {
    text: "이게 우리가 AI를 무작정 두려워하기보다,",
    startFrame: 2128,
    endFrame: 2207
  },
  {
    text: "똑바로 알고 공부해야 하는 이유입니다.",
    startFrame: 2207,
    endFrame: 2268
  },
  {
    text: "나만 모르면 진짜 영화 속 엑스트라처럼 휩쓸려 갈 수",
    startFrame: 2268,
    endFrame: 2369
  },
  {
    text: "있으니까요. 오늘 제 얘기가 '아,",
    startFrame: 2369,
    endFrame: 2459
  },
  {
    text: "세상이 진짜 이렇게 돌아가고 있구나' 하고 조금이라도",
    startFrame: 2459,
    endFrame: 2538
  },
  {
    text: "와닿으셨다면 구독 한번 꾹 눌러주세요.",
    startFrame: 2538,
    endFrame: 2618
  },
  {
    text: "그리고 영상 끄기 전에 댓글로 이거 하나만 남겨주세요.",
    startFrame: 2618,
    endFrame: 2721
  },
  {
    text: "'내 목숨이 걸린 전쟁터, 사람 사령관을 믿을 것인가,",
    startFrame: 2721,
    endFrame: 2828
  },
  {
    text: "냉철한 AI를 믿을 것인가?'",
    startFrame: 2828,
    endFrame: 2888
  },
];
