// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "이제 귀찮은 자료 조사나 요약은 인공지능에게 맡기고 더",
    startFrame: 0,
    endFrame: 125
  },
  {
    text: "가치 있는 일을 하세요.",
    startFrame: 125,
    endFrame: 158
  },
  {
    text: "이 작은 변화들이 모여 당신의 하루에 2시간이라는",
    startFrame: 158,
    endFrame: 262
  },
  {
    text: "여유를 선물할 겁니다.",
    startFrame: 262,
    endFrame: 311
  },
  {
    text: "더 구체적인 활용법이 궁금하다면 고정 댓글의",
    startFrame: 311,
    endFrame: 410
  },
  {
    text: "링크를 확인해 보세요.",
    startFrame: 410,
    endFrame: 468
  },
  {
    text: "오늘 영상이 도움 되셨다면 구독과 좋아요 부탁드립니다!",
    startFrame: 468,
    endFrame: 595
  },
];
