// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "여러분,",
    startFrame: 0,
    endFrame: 14
  },
  {
    text: "혹시 오늘도 '시간이 없다'는 말을 입에 달고 사셨나요?",
    startFrame: 14,
    endFrame: 128
  },
  {
    text: "사실 우리가 바쁜 이유는 능력이 부족해서가",
    startFrame: 128,
    endFrame: 203
  },
  {
    text: "아니라 도구가 없어서입니다.",
    startFrame: 203,
    endFrame: 293
  },
  {
    text: "오늘은 제 삶의 질을 180도 바꿔준 세",
    startFrame: 293,
    endFrame: 385
  },
  {
    text: "가지 아이템을 소개할게요.",
    startFrame: 385,
    endFrame: 452
  },
  {
    text: "첫 번째는 모든 기록을 자동화해 주는",
    startFrame: 452,
    endFrame: 526
  },
  {
    text: "스마트 노션 템플릿입니다.",
    startFrame: 526,
    endFrame: 574
  },
];
