// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "2026년 3월 26일,",
    startFrame: 0,
    endFrame: 69
  },
  {
    text: "Anthropic의 내부 문서가 유출되었는데,",
    startFrame: 69,
    endFrame: 150
  },
  {
    text: "거기엔 이렇게 적혀있었습니다.",
    startFrame: 150,
    endFrame: 203
  },
  {
    text: "\"역대 어떤 AI보다 사이버 능력이 압도적으로 앞선다.\"",
    startFrame: 203,
    endFrame: 324
  },
  {
    text: "Mythos에 대한 정보가 세상에 공개되고 사이버보안 관련",
    startFrame: 324,
    endFrame: 420
  },
  {
    text: "주가는 전부 폭락했습니다.",
    startFrame: 420,
    endFrame: 470
  },
  {
    text: "대체 어느 정도의 성능을 가졌길래 전 세계가 충격에",
    startFrame: 470,
    endFrame: 557
  },
  {
    text: "빠졌을까요? AI 탈출사건,",
    startFrame: 557,
    endFrame: 598
  },
  {
    text: "테스트 점수 조작,",
    startFrame: 598,
    endFrame: 656
  },
  {
    text: "opus4.7의 성능을 낮춰야만 했던",
    startFrame: 674,
    endFrame: 747
  },
  {
    text: "이유까지 전부 파헤쳐보겠습니다.",
    startFrame: 747,
    endFrame: 800
  },
];
