// AUTO-GENERATED by scripts/update-gallery.py — 직접 수정하지 마세요.
// 컴포넌트에 `// @gallery: <Component ... />` 주석을 추가하고 스크립트를 재실행하세요.
import React from 'react';
import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring } from 'remotion';
import { BrandLogo } from './BrandLogo';
import { ChatBriefing } from './ChatBriefing';
import { DataNetwork } from './DataNetwork';
import { DataStream } from './DataStream';
import { EndingCard } from './EndingCard';
import { EventTimeline } from './EventTimeline';
import { GavelIcon } from './GavelIcon';
import { MatrixTunnel } from './MatrixTunnel';
import { NuclearControl } from './NuclearControl';
import { ScanOverlay } from './ScanOverlay';
import { StatChart } from './StatChart';
import { StatedDocument } from './StatedDocument';
import { SwarmGrid } from './SwarmGrid';
import { TacticalDash } from './TacticalDash';
import { UniquePosition } from './UniquePosition';
import { VersusLayout } from './VersusLayout';

const GALLERY_ITEMS: Array<{ label: string; element: (p: number) => React.ReactNode }> = [
  { label: 'BrandLogo', element: (p: number) => <BrandLogo type="Claude" progress={p} size={120} /> },
  { label: 'ChatBriefing', element: (p: number) => <ChatBriefing progress={p} /> },
  { label: 'DataNetwork', element: (p: number) => <DataNetwork type="grid" progress={p} /> },
  { label: 'DataStream', element: (p: number) => <DataStream progress={p} /> },
  { label: 'EndingCard', element: (p: number) => <EndingCard progress={p} /> },
  { label: 'EventTimeline', element: (p: number) => <EventTimeline type="tragedy" progress={p} /> },
  { label: 'GavelIcon', element: (p: number) => <GavelIcon progress={p} /> },
  { label: 'MatrixTunnel', element: (p: number) => <MatrixTunnel progress={p} /> },
  { label: 'NuclearControl', element: (p: number) => <NuclearControl progress={p} /> },
  { label: 'ScanOverlay', element: (p: number) => <ScanOverlay progress={p} /> },
  { label: 'StatChart', element: (p: number) => <StatChart type="growth" progress={p} /> },
  { label: 'StatedDocument', element: (p: number) => <StatedDocument type="target" progress={p} title="표적 보고서" /> },
  { label: 'SwarmGrid', element: (p: number) => <SwarmGrid progress={p} /> },
  { label: 'TacticalDash', element: (p: number) => <TacticalDash type="drone" progress={p} /> },
  { label: 'UniquePosition', element: (p: number) => <UniquePosition progress={p} /> },
  { label: 'VersusLayout', element: (p: number) => <VersusLayout progress={p} leftLabel="HUMAN" rightLabel="AI" /> },
];

const CARD_H = 600;
const LABEL_H = 36;

export const ComponentGallery: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  
  // Create a ping-pong progress from 0 to 1 over 60 frames
  const loopDuration = 60;
  const cycle = Math.floor(frame / loopDuration);
  const cycleFrame = frame % loopDuration;
  const rawP = cycleFrame / loopDuration;
  
  // Eased progress (ping-pong)
  const p = cycle % 2 === 0 
    ? 1 - Math.pow(1 - rawP, 3) 
    : Math.pow(1 - rawP, 3);

  return (
    <AbsoluteFill
      style={{
        background: '#F5F0EB',
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        alignContent: 'start',
        overflowY: 'auto',
      }}
    >
      {GALLERY_ITEMS.length === 0 && (
        <div style={{ margin: 'auto', color: '#BBB', fontFamily: 'monospace', fontSize: 28 }}>
          Gallery is empty — add @gallery comments to components
        </div>
      )}
      {GALLERY_ITEMS.map(({ label, element }) => (
        <div
          key={label}
          style={{
            height: CARD_H,
            boxSizing: 'border-box',
            border: '1px solid #DDD',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
          }}
        >
          <div style={{
            height: LABEL_H,
            padding: '0 12px',
            lineHeight: `${LABEL_H}px`,
            fontFamily: 'monospace',
            fontSize: 18,
            color: '#888',
            borderBottom: '1px solid #EEE',
            background: '#FFF',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            position: 'relative',
            zIndex: 10,
          }}>
            {label}
          </div>
          <div style={{
            flex: 1,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 16,
            position: 'relative',
            overflow: 'auto',
          }}>
            {element(p)}
          </div>
        </div>
      ))}
    </AbsoluteFill>
  );
};
