// AUTO-GENERATED by scripts/update-gallery.py — 직접 수정하지 마세요.
import React from 'react';
import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring } from 'remotion';
import { Body3BattlefieldSketch } from './svg/Body3BattlefieldSketch';
import { Body3GavelIcon } from './svg/Body3GavelIcon';
import { Body3MilitaryIcon } from './svg/Body3MilitaryIcon';
import { Body3MissingIcon } from './svg/Body3MissingIcon';
import { Body3SurveillanceIcon } from './svg/Body3SurveillanceIcon';
import { Body3WeaponIcon } from './svg/Body3WeaponIcon';
import { Body1_Drone } from './svg/body1_Drone';
import { Body2AIIcon } from './svg/body2_AIIcon';
import { Body2AnalystGroup } from './svg/body2_AnalystGroup';
import { Body2AnalystIcon } from './svg/body2_AnalystIcon';
import { Body2Crosshair } from './svg/body2_Crosshair';
import { Body2DataFlow } from './svg/body2_DataFlow';
import { Body2DataIcons } from './svg/body2_DataIcons';
import { Body2ScanLine } from './svg/body2_ScanLine';
import { Body2SignalIcon } from './svg/body2_SignalIcon';
import { Body2SocialIcon } from './svg/body2_SocialIcon';
import { Body2Waveform } from './svg/body2_Waveform';
import { body4_FolderSketch } from './svg/body4_FolderSketch';
import { body4_LetterSketch } from './svg/body4_LetterSketch';
import { body4_QuestionMark } from './svg/body4_QuestionMark';
import { body4_SchoolSketch } from './svg/body4_SchoolSketch';
import { body4_WarningSketch } from './svg/body4_WarningSketch';
import { IntroAiBoxes } from './svg/intro_AiBoxes';
import { IntroAiCore } from './svg/intro_AiCore';
import { IntroTargetGrid } from './svg/intro_TargetGrid';
import { IntroUnderline } from './svg/intro_Underline';
import { IntroWarningIcon } from './svg/intro_WarningIcon';
import { Body2ReportCard } from './ui/body2_ReportCard';

const SVG_ITEMS: Array<{ label: string; element: (props: any) => React.ReactNode }> = [
  {
    label: 'Body3BattlefieldSketch',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body3BattlefieldSketch as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body3GavelIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body3GavelIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body3MilitaryIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body3MilitaryIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body3MissingIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body3MissingIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body3SurveillanceIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body3SurveillanceIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body3WeaponIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body3WeaponIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body1_Drone',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body1_Drone as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2AIIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2AIIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2AnalystGroup',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2AnalystGroup as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2AnalystIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2AnalystIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2Crosshair',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2Crosshair as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2DataFlow',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2DataFlow as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2DataIcons',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2DataIcons as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2ScanLine',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2ScanLine as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2SignalIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2SignalIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2SocialIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2SocialIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Body2Waveform',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2Waveform as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'body4_FolderSketch',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = body4_FolderSketch as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'body4_LetterSketch',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = body4_LetterSketch as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'body4_QuestionMark',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = body4_QuestionMark as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'body4_SchoolSketch',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = body4_SchoolSketch as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'body4_WarningSketch',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = body4_WarningSketch as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'IntroAiBoxes',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = IntroAiBoxes as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'IntroAiCore',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = IntroAiCore as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'IntroTargetGrid',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = IntroTargetGrid as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'IntroUnderline',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = IntroUnderline as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'IntroWarningIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = IntroWarningIcon as any;
      return <Comp {...props} />;
    }
  },];

const UI_ITEMS: Array<{ label: string; element: (props: any) => React.ReactNode }> = [
  {
    label: 'Body2ReportCard',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Body2ReportCard as any;
      return <Comp {...props} />;
    }
  },];

class ErrorBoundary extends React.Component<{children: React.ReactNode}, {hasError: boolean, error: Error | null}> {
  constructor(props: {children: React.ReactNode}) {
    super(props);
    this.state = { hasError: false, error: null };
  }
  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error };
  }
  render() {
    if (this.state.hasError) {
      return (
        <div style={{ color: '#D32F2F', textAlign: 'center', padding: 20 }}>
          <h3 style={{ margin: '0 0 8px 0', fontSize: 16 }}>Rendering Error</h3>
          <pre style={{ fontSize: 11, whiteSpace: 'pre-wrap', wordBreak: 'break-all', margin: 0 }}>{this.state.error?.message}</pre>
        </div>
      );
    }
    return this.props.children;
  }
}

const CARD_H = 600;
const LABEL_H = 36;

export const ComponentGallery: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  // 160프레임 주기로 반복되는 루프 (0->1->0 핑퐁)
  const loopFrame = frame % 160;
  const enter = spring({ frame: loopFrame - 20, fps, config: { damping: 14, stiffness: 120 } });
  const exit = spring({ frame: loopFrame - 140, fps, config: { damping: 14, stiffness: 120 } });
  const progress = enter - exit;

  const renderGrid = (title: string, items: typeof SVG_ITEMS) => (
    <div style={{ padding: '40px' }}>
      <h2 style={{ fontFamily: 'sans-serif', fontSize: 32, marginBottom: 20 }}>{title} ({items.length})</h2>
      {items.length === 0 ? (
        <div style={{ color: '#BBB', fontFamily: 'monospace', fontSize: 20 }}>해당 폴더에 컴포넌트가 없습니다.</div>
      ) : (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '20px',
        }}>
          {items.map(({ label, element }) => (
            <div
              key={label}
              style={{
                height: CARD_H,
                boxSizing: 'border-box',
                border: '1px solid #DDD',
                background: '#FFF',
                display: 'flex',
                flexDirection: 'column',
                overflow: 'hidden',
                borderRadius: 12,
                boxShadow: '0 4px 12px rgba(0,0,0,0.05)'
              }}
            >
              <div style={{
                height: LABEL_H,
                padding: '0 16px',
                lineHeight: `${LABEL_H}px`,
                fontFamily: 'monospace',
                fontSize: 16,
                fontWeight: 'bold',
                color: '#555',
                borderBottom: '1px solid #EEE',
                background: '#FAFAFA',
              }}>
                {label}
              </div>
              <div style={{
                flex: 1,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                padding: 16,
                position: 'relative',
                overflow: 'auto',
              }}>
                <ErrorBoundary>
                  {element({ progress, strikeProgress: progress, revealClaude: progress })}
                </ErrorBoundary>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <AbsoluteFill style={{ background: '#F5F0EB', overflowY: 'auto' }}>
      {renderGrid("🎨 SVG 그림 컴포넌트 (components/svg/)", SVG_ITEMS)}
      {renderGrid("🧩 일반 UI 컴포넌트 (components/ui/)", UI_ITEMS)}
    </AbsoluteFill>
  );
};
