// AUTO-GENERATED by scripts/update-gallery.py — 직접 수정하지 마세요.
// 컴포넌트에 `// @gallery: <Component ... />` 주석을 추가하고 스크립트를 재실행하세요.
import React from 'react';
import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring } from 'remotion';
import { AIBrain } from './AIBrain';
import { AISymbols } from './AISymbols';
import { AccuracyTargets } from './AccuracyTargets';
import { AlgorithmTree } from './AlgorithmTree';
import { AnalogTimer } from './AnalogTimer';
import { AntennaPing } from './AntennaPing';
import { AnthropicLogo } from './AnthropicLogo';
import { BalanceScale } from './BalanceScale';
import { BatteryGauge } from './BatteryGauge';
import { Beaker } from './Beaker';
import { BigBenStamp } from './BigBenStamp';
import { BrickWall } from './BrickWall';
import { BriefingFolder } from './BriefingFolder';
import { CampingCarSilhouette } from './CampingCarSilhouette';
import { ChainedClaude } from './ChainedClaude';
import { ChalkboardBg } from './ChalkboardBg';
import { ChecklistEfficiency } from './ChecklistEfficiency';
import { ChildSilhouettes } from './ChildSilhouettes';
import { CircuitBoard } from './CircuitBoard';
import { ClaudeFunnel } from './ClaudeFunnel';
import { ClaudeInWheel } from './ClaudeInWheel';
import { ClaudeLogo } from './ClaudeLogo';
import { ClaudeWithPointer } from './ClaudeWithPointer';
import { ClipPathExpand } from './ClipPathExpand';
import { ColorTransitionTank } from './ColorTransitionTank';
import { CombatDrone } from './CombatDrone';
import { CommentUI } from './CommentUI';
import { ConveyorBelt } from './ConveyorBelt';
import { CrackEffect } from './CrackEffect';
import { CrownedAILogos } from './CrownedAILogos';
import { CursorClick } from './CursorClick';
import { CurvedArrow } from './CurvedArrow';
import { DataBlocks } from './DataBlocks';
import { DateCalendar } from './DateCalendar';
import { DeskCalendar } from './DeskCalendar';
import { DespairHuman } from './DespairHuman';
import { DottedRoute } from './DottedRoute';
import { DroneUI } from './DroneUI';
import { EraserHand } from './EraserHand';
import { ExhaustedPerson } from './ExhaustedPerson';
import { ExplosionLines } from './ExplosionLines';
import { FallingLetters } from './FallingLetters';
import { FamilyStickmen } from './FamilyStickmen';
import { FightingStickmen } from './FightingStickmen';
import { FilmFrame } from './FilmFrame';
import { FingerPress } from './FingerPress';
import { Gavel } from './Gavel';
import { GiantRobotHand } from './GiantRobotHand';
import { GiantWave } from './GiantWave';
import { GiantXMark } from './GiantXMark';
import { GlitchText } from './GlitchText';
import { Globe3D } from './Globe3D';
import { GlowingBulb } from './GlowingBulb';
import { GridMonitors } from './GridMonitors';
import { GridUI } from './GridUI';
import { HackerSilhouette } from './HackerSilhouette';
import { HumanBrain } from './HumanBrain';
import { JournalistMic } from './JournalistMic';
import { LargeQuestionMark } from './LargeQuestionMark';
import { LaunchButton } from './LaunchButton';
import { MagnifyingGlass } from './MagnifyingGlass';
import { MatrixCode } from './MatrixCode';
import { MavenTypography } from './MavenTypography';
import { MilitaryBase } from './MilitaryBase';
import { MilitaryHelmet } from './MilitaryHelmet';
import { MiniDrones } from './MiniDrones';
import { MissileIcon } from './MissileIcon';
import { MultiplierStamp } from './MultiplierStamp';
import { NetworkNodes } from './NetworkNodes';
import { Newspaper } from './Newspaper';
import { NukeIcon } from './NukeIcon';
import { OldFloppyDisk } from './OldFloppyDisk';
import { PentagonBuilding } from './PentagonBuilding';
import { PickupTruck } from './PickupTruck';
import { PinIcon } from './PinIcon';
import { PixelRobot } from './PixelRobot';
import { PointingHand } from './PointingHand';
import { PoisonDropper } from './PoisonDropper';
import { ProhibitedMark } from './ProhibitedMark';
import { QuestionTypography } from './QuestionTypography';
import { RadarWaves } from './RadarWaves';
import { RadiantHalo } from './RadiantHalo';
import { ReceiptPrint } from './ReceiptPrint';
import { ResearchPapers } from './ResearchPapers';
import { RobotScissors } from './RobotScissors';
import { RoundTable } from './RoundTable';
import { RuinedSchool } from './RuinedSchool';
import { Satellite } from './Satellite';
import { ScatteredBags } from './ScatteredBags';
import { SchoolBuilding } from './SchoolBuilding';
import { SecretFolder } from './SecretFolder';
import { SignboardChange } from './SignboardChange';
import { SkullIcon } from './SkullIcon';
import { SmokePillar } from './SmokePillar';
import { SocialPopup } from './SocialPopup';
import { SoldierSilhouette } from './SoldierSilhouette';
import { SpeechBubble } from './SpeechBubble';
import { SplitCanvas } from './SplitCanvas';
import { StampText } from './StampText';
import { StickmanCrowd } from './StickmanCrowd';
import { StormClouds } from './StormClouds';
import { StudyBook } from './StudyBook';
import { SubscribeButton } from './SubscribeButton';
import { SurveillanceEyes } from './SurveillanceEyes';
import { SweptStickmen } from './SweptStickmen';
import { TangledQuestion } from './TangledQuestion';
import { TankSilhouette } from './TankSilhouette';
import { TapePile } from './TapePile';
import { TargetStamp } from './TargetStamp';
import { TerminalScreen } from './TerminalScreen';
import { TerminalWindow } from './TerminalWindow';
import { TerritoryFlags } from './TerritoryFlags';
import { TextPrompt } from './TextPrompt';
import { TimelineBar } from './TimelineBar';
import { TomahawkMissile } from './TomahawkMissile';
import { TrackingBox } from './TrackingBox';
import { TrustMeter } from './TrustMeter';
import { TugOfWarOil } from './TugOfWarOil';
import { UncleSamBot } from './UncleSamBot';
import { VictimsText } from './VictimsText';
import { VoiceWave } from './VoiceWave';
import { WarningMark } from './WarningMark';
import { WarningTape } from './WarningTape';
import { WeaponsSketch } from './WeaponsSketch';
import { WorldMap } from './WorldMap';

const GALLERY_ITEMS: Array<{ label: string; element: (p: number) => React.ReactNode }> = [
  { label: 'AIBrain', element: (p: number) => <AIBrain progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'AISymbols', element: (p: number) => <AISymbols progress={p} color="#2A363B" size={80} strokeWidth={3} type="GPT" /> },
  { label: 'AccuracyTargets', element: (p: number) => <AccuracyTargets progress={p} color="#2A363B" size={400} strokeWidth={3} /> },
  { label: 'AlgorithmTree', element: (p: number) => <AlgorithmTree progress={p} color="#99B898" width={400} height={300} strokeWidth={2} /> },
  { label: 'AnalogTimer', element: (p: number) => <AnalogTimer progress={p} color="#2A363B" size={150} strokeWidth={4} /> },
  { label: 'AntennaPing', element: (p: number) => <AntennaPing progress={p} color="#99B898" size={100} strokeWidth={3} /> },
  { label: 'AnthropicLogo', element: (p: number) => <AnthropicLogo progress={p} color="#E8A87C" width={300} height={100} strokeWidth={3} /> },
  { label: 'BalanceScale', element: (p: number) => <BalanceScale progress={p} color="#2A363B" width={400} height={300} strokeWidth={4} /> },
  { label: 'BatteryGauge', element: (p: number) => <BatteryGauge progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'Beaker', element: (p: number) => <Beaker progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'BigBenStamp', element: (p: number) => <BigBenStamp progress={p} color="#E84A5F" size={150} strokeWidth={3} /> },
  { label: 'BrickWall', element: (p: number) => <BrickWall progress={p} color="#4C5B5C" width={100} height={200} strokeWidth={2} /> },
  { label: 'BriefingFolder', element: (p: number) => <BriefingFolder progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'CampingCarSilhouette', element: (p: number) => <CampingCarSilhouette progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'ChainedClaude', element: (p: number) => <ChainedClaude progress={p} color="#E8A87C" size={150} strokeWidth={3} /> },
  { label: 'ChalkboardBg', element: (p: number) => <ChalkboardBg progress={p} color="#2A363B" width={300} height={200} strokeWidth={2} /> },
  { label: 'ChecklistEfficiency', element: (p: number) => <ChecklistEfficiency progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'ChildSilhouettes', element: (p: number) => <ChildSilhouettes progress={p} color="#E8A87C" size={400} strokeWidth={2} /> },
  { label: 'CircuitBoard', element: (p: number) => <CircuitBoard progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'ClaudeFunnel', element: (p: number) => <ClaudeFunnel progress={p} color="#E8A87C" size={150} strokeWidth={3} /> },
  { label: 'ClaudeInWheel', element: (p: number) => <ClaudeInWheel progress={p} color="#E8A87C" size={150} strokeWidth={3} /> },
  { label: 'ClaudeLogo', element: (p: number) => <ClaudeLogo progress={p} color="#E8A87C" size={120} strokeWidth={4} /> },
  { label: 'ClaudeWithPointer', element: (p: number) => <ClaudeWithPointer progress={p} color="#E8A87C" size={200} strokeWidth={3} /> },
  { label: 'ClipPathExpand', element: (p: number) => <ClipPathExpand progress={p} color="#1A1C20" width={400} height={300} /> },
  { label: 'ColorTransitionTank', element: (p: number) => <ColorTransitionTank progress={p} width={200} height={300} strokeWidth={3} /> },
  { label: 'CombatDrone', element: (p: number) => <CombatDrone progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'CommentUI', element: (p: number) => <CommentUI progress={p} width={500} height={200} strokeWidth={3} /> },
  { label: 'ConveyorBelt', element: (p: number) => <ConveyorBelt progress={p} color="#2A363B" width={300} height={100} strokeWidth={3} /> },
  { label: 'CrackEffect', element: (p: number) => <CrackEffect progress={p} color="#E8A87C" size={150} strokeWidth={3} /> },
  { label: 'CrownedAILogos', element: (p: number) => <CrownedAILogos progress={p} color="#2A363B" width={300} height={150} /> },
  { label: 'CursorClick', element: (p: number) => <CursorClick progress={p} size={150} strokeWidth={3} /> },
  { label: 'CurvedArrow', element: (p: number) => <CurvedArrow progress={p} color="#E84A5F" size={150} strokeWidth={4} startX={20} startY={120} endX={130} endY={50} curveOffset={30} /> },
  { label: 'DataBlocks', element: (p: number) => <DataBlocks progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'DateCalendar', element: (p: number) => <DateCalendar progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'DeskCalendar', element: (p: number) => <DeskCalendar progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'DespairHuman', element: (p: number) => <DespairHuman progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'DottedRoute', element: (p: number) => <DottedRoute progress={p} color="#E84A5F" width={200} height={150} strokeWidth={3} /> },
  { label: 'DroneUI', element: (p: number) => <DroneUI progress={p} color="#E84A5F" size={200} strokeWidth={2} /> },
  { label: 'EraserHand', element: (p: number) => <EraserHand progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'ExhaustedPerson', element: (p: number) => <ExhaustedPerson progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'ExplosionLines', element: (p: number) => <ExplosionLines progress={p} color="#E84A5F" size={200} strokeWidth={4} /> },
  { label: 'FallingLetters', element: (p: number) => <FallingLetters progress={p} color="#2A363B" size={400} strokeWidth={2} /> },
  { label: 'FamilyStickmen', element: (p: number) => <FamilyStickmen progress={p} color="#2A363B" size={200} strokeWidth={4} /> },
  { label: 'FightingStickmen', element: (p: number) => <FightingStickmen progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'FilmFrame', element: (p: number) => <FilmFrame progress={p} width={400} height={300} /> },
  { label: 'FingerPress', element: (p: number) => <FingerPress progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'Gavel', element: (p: number) => <Gavel progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'GiantRobotHand', element: (p: number) => <GiantRobotHand progress={p} color="#2A363B" size={400} strokeWidth={5} /> },
  { label: 'GiantWave', element: (p: number) => <GiantWave progress={p} color="#99B898" width={600} height={400} strokeWidth={3} /> },
  { label: 'GiantXMark', element: (p: number) => <GiantXMark progress={p} color="#E84A5F" size={200} strokeWidth={6} /> },
  { label: 'GlitchText', element: (p: number) => <GlitchText progress={p} text="NEW WARS" color="#E84A5F" width={400} height={150} /> },
  { label: 'Globe3D', element: (p: number) => <Globe3D progress={p} color="#2A363B" size={200} strokeWidth={2} /> },
  { label: 'GlowingBulb', element: (p: number) => <GlowingBulb progress={p} color="#E8A87C" size={150} strokeWidth={3} /> },
  { label: 'GridMonitors', element: (p: number) => <GridMonitors progress={p} width={400} height={300} /> },
  { label: 'GridUI', element: (p: number) => <GridUI progress={p} color="#99B898" size={200} strokeWidth={1} /> },
  { label: 'HackerSilhouette', element: (p: number) => <HackerSilhouette progress={p} color="#1A1C20" size={250} strokeWidth={3} /> },
  { label: 'HumanBrain', element: (p: number) => <HumanBrain progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'JournalistMic', element: (p: number) => <JournalistMic progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'LargeQuestionMark', element: (p: number) => <LargeQuestionMark progress={p} color="#E84A5F" size={150} strokeWidth={5} /> },
  { label: 'LaunchButton', element: (p: number) => <LaunchButton progress={p} color="#E84A5F" size={150} strokeWidth={4} /> },
  { label: 'MagnifyingGlass', element: (p: number) => <MagnifyingGlass progress={p} color="#2A363B" size={100} strokeWidth={4} /> },
  { label: 'MatrixCode', element: (p: number) => <MatrixCode progress={p} color="#99B898" width={300} height={200} /> },
  { label: 'MavenTypography', element: (p: number) => <MavenTypography progress={p} color="#2A363B" size={300} /> },
  { label: 'MilitaryBase', element: (p: number) => <MilitaryBase progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'MilitaryHelmet', element: (p: number) => <MilitaryHelmet progress={p} color="#2A363B" size={120} strokeWidth={4} /> },
  { label: 'MiniDrones', element: (p: number) => <MiniDrones progress={p} color="#2A363B" size={150} strokeWidth={2} /> },
  { label: 'MissileIcon', element: (p: number) => <MissileIcon progress={p} color="#E84A5F" size={100} strokeWidth={2} /> },
  { label: 'MultiplierStamp', element: (p: number) => <MultiplierStamp progress={p} color="#E84A5F" size={200} strokeWidth={4} /> },
  { label: 'NetworkNodes', element: (p: number) => <NetworkNodes progress={p} color="#2A363B" size={200} strokeWidth={2} /> },
  { label: 'Newspaper', element: (p: number) => <Newspaper progress={p} color="#2A363B" size={150} strokeWidth={2} /> },
  { label: 'NukeIcon', element: (p: number) => <NukeIcon progress={p} color="#E84A5F" size={150} strokeWidth={3} /> },
  { label: 'OldFloppyDisk', element: (p: number) => <OldFloppyDisk progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'PentagonBuilding', element: (p: number) => <PentagonBuilding progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'PickupTruck', element: (p: number) => <PickupTruck progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'PinIcon', element: (p: number) => <PinIcon progress={p} color="#2A363B" size={80} strokeWidth={3} type="shield" /> },
  { label: 'PixelRobot', element: (p: number) => <PixelRobot progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'PointingHand', element: (p: number) => <PointingHand progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'PoisonDropper', element: (p: number) => <PoisonDropper progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'ProhibitedMark', element: (p: number) => <ProhibitedMark progress={p} color="#E84A5F" size={150} strokeWidth={6} /> },
  { label: 'QuestionTypography', element: (p: number) => <QuestionTypography progress={p} text="AI가 그 학교를 표적으로 선정했습니까?" color="#2A363B" size={600} /> },
  { label: 'RadarWaves', element: (p: number) => <RadarWaves progress={p} color="#99B898" size={150} strokeWidth={2} /> },
  { label: 'RadiantHalo', element: (p: number) => <RadiantHalo progress={p} color="#E8A87C" size={200} strokeWidth={3} /> },
  { label: 'ReceiptPrint', element: (p: number) => <ReceiptPrint progress={p} color="#2A363B" size={150} strokeWidth={2} /> },
  { label: 'ResearchPapers', element: (p: number) => <ResearchPapers progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'RobotScissors', element: (p: number) => <RobotScissors progress={p} color="#2A363B" size={200} strokeWidth={4} /> },
  { label: 'RoundTable', element: (p: number) => <RoundTable progress={p} color="#2A363B" width={400} height={200} strokeWidth={4} /> },
  { label: 'RuinedSchool', element: (p: number) => <RuinedSchool progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'Satellite', element: (p: number) => <Satellite progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'ScatteredBags', element: (p: number) => <ScatteredBags progress={p} color="#99B898" size={300} strokeWidth={3} /> },
  { label: 'SchoolBuilding', element: (p: number) => <SchoolBuilding progress={p} color="#2A363B" width={200} height={150} strokeWidth={3} isRuined={false} /> },
  { label: 'SecretFolder', element: (p: number) => <SecretFolder progress={p} color="#2A363B" width={200} height={150} strokeWidth={3} /> },
  { label: 'SignboardChange', element: (p: number) => <SignboardChange progress={p} color="#2A363B" width={300} height={150} strokeWidth={3} /> },
  { label: 'SkullIcon', element: (p: number) => <SkullIcon progress={p} color="#E84A5F" size={150} strokeWidth={3} /> },
  { label: 'SmokePillar', element: (p: number) => <SmokePillar progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'SocialPopup', element: (p: number) => <SocialPopup progress={p} color="#2A363B" size={150} strokeWidth={2} /> },
  { label: 'SoldierSilhouette', element: (p: number) => <SoldierSilhouette progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'SpeechBubble', element: (p: number) => <SpeechBubble progress={p} color="#2A363B" width={200} height={120} strokeWidth={3} /> },
  { label: 'SplitCanvas', element: (p: number) => <SplitCanvas progress={p} color="#2A363B" width={300} height={200} strokeWidth={2} /> },
  { label: 'StampText', element: (p: number) => <StampText progress={p} color="#E84A5F" text="TOP SECRET" size={200} strokeWidth={4} /> },
  { label: 'StickmanCrowd', element: (p: number) => <StickmanCrowd progress={p} color="#2A363B" size={300} strokeWidth={2} count={50} /> },
  { label: 'StormClouds', element: (p: number) => <StormClouds progress={p} color="#1A1C20" width={400} height={200} /> },
  { label: 'StudyBook', element: (p: number) => <StudyBook progress={p} color="#2A363B" size={300} strokeWidth={3} /> },
  { label: 'SubscribeButton', element: (p: number) => <SubscribeButton progress={p} width={300} height={100} /> },
  { label: 'SurveillanceEyes', element: (p: number) => <SurveillanceEyes progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'SweptStickmen', element: (p: number) => <SweptStickmen progress={p} color="#2A363B" size={400} strokeWidth={2} /> },
  { label: 'TangledQuestion', element: (p: number) => <TangledQuestion progress={p} color="#E84A5F" size={150} strokeWidth={3} /> },
  { label: 'TankSilhouette', element: (p: number) => <TankSilhouette progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'TapePile', element: (p: number) => <TapePile progress={p} color="#2A363B" size={150} strokeWidth={3} /> },
  { label: 'TargetStamp', element: (p: number) => <TargetStamp progress={p} color="#E84A5F" size={150} strokeWidth={4} /> },
  { label: 'TerminalScreen', element: (p: number) => <TerminalScreen progress={p} color="#99B898" width={300} height={200} /> },
  { label: 'TerminalWindow', element: (p: number) => <TerminalWindow progress={p} color="#2A363B" width={180} height={120} strokeWidth={3} /> },
  { label: 'TerritoryFlags', element: (p: number) => <TerritoryFlags progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'TextPrompt', element: (p: number) => <TextPrompt progress={p} color="#99B898" width={200} height={80} strokeWidth={3} /> },
  { label: 'TimelineBar', element: (p: number) => <TimelineBar progress={p} color="#E84A5F" width={300} height={50} /> },
  { label: 'TomahawkMissile', element: (p: number) => <TomahawkMissile progress={p} color="#2A363B" size={300} strokeWidth={4} /> },
  { label: 'TrackingBox', element: (p: number) => <TrackingBox progress={p} color="#E84A5F" size={150} strokeWidth={4} /> },
  { label: 'TrustMeter', element: (p: number) => <TrustMeter progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'TugOfWarOil', element: (p: number) => <TugOfWarOil progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'UncleSamBot', element: (p: number) => <UncleSamBot progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'VictimsText', element: (p: number) => <VictimsText progress={p} color="#E84A5F" size={300} /> },
  { label: 'VoiceWave', element: (p: number) => <VoiceWave progress={p} color="#E8A87C" width={200} height={100} strokeWidth={3} /> },
  { label: 'WarningMark', element: (p: number) => <WarningMark progress={p} color="#E84A5F" size={100} strokeWidth={4} /> },
  { label: 'WarningTape', element: (p: number) => <WarningTape progress={p} width={400} height={100} strokeWidth={3} /> },
  { label: 'WeaponsSketch', element: (p: number) => <WeaponsSketch progress={p} color="#2A363B" size={200} strokeWidth={3} /> },
  { label: 'WorldMap', element: (p: number) => <WorldMap progress={p} color="#2A363B" width={300} height={150} strokeWidth={2} /> },
];

const CARD_H = 320;
const LABEL_H = 36;

export const ComponentGallery: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  
  // Create a ping-pong progress from 0 to 1 over 60 frames
  const loopDuration = 60;
  const cycle = Math.floor(frame / loopDuration);
  const cycleFrame = frame % loopDuration;
  const rawP = cycleFrame / loopDuration;
  
  // Eased progress (ping-pong)
  const p = cycle % 2 === 0 
    ? 1 - Math.pow(1 - rawP, 3) 
    : Math.pow(1 - rawP, 3);

  return (
    <AbsoluteFill
      style={{
        background: '#F5F0EB',
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        alignContent: 'start',
        overflowY: 'auto',
      }}
    >
      {GALLERY_ITEMS.length === 0 && (
        <div style={{ margin: 'auto', color: '#BBB', fontFamily: 'monospace', fontSize: 28 }}>
          Gallery is empty — add @gallery comments to components
        </div>
      )}
      {GALLERY_ITEMS.map(({ label, element }) => (
        <div
          key={label}
          style={{
            height: CARD_H,
            boxSizing: 'border-box',
            border: '1px solid #DDD',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
          }}
        >
          <div style={{
            height: LABEL_H,
            padding: '0 12px',
            lineHeight: `${LABEL_H}px`,
            fontFamily: 'monospace',
            fontSize: 18,
            color: '#888',
            borderBottom: '1px solid #EEE',
            background: '#FFF',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            position: 'relative',
            zIndex: 10,
          }}>
            {label}
          </div>
          <div style={{
            flex: 1,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 16,
            position: 'relative',
            overflow: 'hidden',
          }}>
            {element(p)}
          </div>
        </div>
      ))}
    </AbsoluteFill>
  );
};
