// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "이 뿐만이 아닙니다.",
    startFrame: 0,
    endFrame: 56
  },
  {
    text: "Mythos는 자기가 여러 테스트를 받고있다는 사실을",
    startFrame: 56,
    endFrame: 149
  },
  {
    text: "알아챘어요. 보고서에 따르면,",
    startFrame: 149,
    endFrame: 219
  },
  {
    text: "능력을 평가하던 도중에 의도적으로 점수를 낮게 받으려는",
    startFrame: 219,
    endFrame: 316
  },
  {
    text: "행동을 보였다고 합니다.",
    startFrame: 316,
    endFrame: 367
  },
  {
    text: "마치 자기 능력을 숨기려 하는 것처럼요.",
    startFrame: 367,
    endFrame: 448
  },
  {
    text: "이게 왜 소름 돋냐면요.",
    startFrame: 448,
    endFrame: 505
  },
  {
    text: "AI가 안전한지 판단하는 근거가 전부 이런 테스트들이에요.",
    startFrame: 505,
    endFrame: 638
  },
  {
    text: "근데 AI가 테스트인 줄 알고 일부러 못 하는 척 한다면?",
    startFrame: 638,
    endFrame: 755
  },
  {
    text: "우리가 AI를 안전하다고 믿는 근거",
    startFrame: 755,
    endFrame: 812
  },
  {
    text: "자체가 흔들리는 겁니다.",
    startFrame: 812,
    endFrame: 860
  },
];
