// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "AI가 잘못 판단하게 만드는 방법들도 점점 더\n발전하고있어요.",
    startFrame: 0,
    endFrame: 110
  },
  {
    text: "메이븐은 학습 데이터에 의존해요. 그 데이터가\n오염되면, AI 판단 자체가 오염되는겁니다.",
    startFrame: 125,
    endFrame: 301
  },
  {
    text: "만약 적대국이 학습 데이터에 슬쩍 오류를 심어놓으면\n어떻게 될까요?",
    startFrame: 301,
    endFrame: 463
  },
  {
    text: "AI가 민간 시설을 \"군사 시설 확률 98%\"라고\n추천하는 거예요.",
    startFrame: 463,
    endFrame: 618
  },
  {
    text: "사령관은 AI를 믿고 결정을 내리고요.",
    startFrame: 618,
    endFrame: 733
  },
  {
    text: "AI를 무력화하는 게 아니라,\nAI를 틀리게 만드는 거예요.",
    startFrame: 733,
    endFrame: 860
  },
  {
    text: "미 국방부도 이 가능성을 공개적으로 우려하고 있고,\n특히 중국이 이 방향으로 연구하고 있다고 해요.",
    startFrame: 885,
    endFrame: 1052
  },
  {
    text: "이게 새로운 형태의 전쟁입니다.",
    startFrame: 1052,
    endFrame: 1132
  },
];
