// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "근데 여기서 반전이 있어요.",
    startFrame: 0,
    endFrame: 47
  },
  {
    text: "사실 클로드를 만든 앤트로픽은 미국이 클로드를 군사적",
    startFrame: 47,
    endFrame: 171
  },
  {
    text: "목적으로 쓰는걸 원하지 않았습니다.",
    startFrame: 171,
    endFrame: 230
  },
  {
    text: "앤트로픽은 펜타곤에 클로드 사용 조건을 달았는데 이런",
    startFrame: 230,
    endFrame: 326
  },
  {
    text: "거에요. \"클로드를 자율 무기에 쓰는 건 안 됩니다.",
    startFrame: 326,
    endFrame: 439
  },
  {
    text: "미국인 대량 감시에도 안 됩니다.\"",
    startFrame: 439,
    endFrame: 511
  },
  {
    text: "그러자 트럼프 행정부가 앤트로픽을 공급망",
    startFrame: 511,
    endFrame: 592
  },
  {
    text: "위험 기업으로 지정해버렸어요.",
    startFrame: 592,
    endFrame: 659
  },
  {
    text: "이 지정은 보통 외국 적대국 기업한테나 쓰는 표현인데 말이",
    startFrame: 659,
    endFrame: 780
  },
  {
    text: "안되는거죠. 당연히 앤트로픽은 즉각 소송을 냈습니다.",
    startFrame: 780,
    endFrame: 917
  },
  {
    text: "근데 진짜 아이러니한 게 있어요.",
    startFrame: 917,
    endFrame: 987
  },
  {
    text: "그 싸움이 한창인 와중에도,",
    startFrame: 987,
    endFrame: 1040
  },
  {
    text: "클로드를 전쟁터에서 계속 돌리고 있었습니다.",
    startFrame: 1040,
    endFrame: 1139
  },
  {
    text: "쫓아내고 싶은데 당장 대체할 게 없으니까,",
    startFrame: 1139,
    endFrame: 1222
  },
  {
    text: "일단 쓰고 보는 거에요.",
    startFrame: 1222,
    endFrame: 1274
  },
];
