// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "오늘 이렇게 mythos의 성능과 여러 사건들에",
    startFrame: 0,
    endFrame: 75
  },
  {
    text: "대해서 알아봤는데요. 어떠셨나요?",
    startFrame: 75,
    endFrame: 148
  },
  {
    text: "이미 많이 발전한 AI는 점점 더 무서운 속도로",
    startFrame: 148,
    endFrame: 252
  },
  {
    text: "발전하는 것 같습니다.",
    startFrame: 252,
    endFrame: 284
  },
  {
    text: "이제는 잘못 사용하면 실제 세상에 큰 위험을 초래할 수도",
    startFrame: 284,
    endFrame: 417
  },
  {
    text: "있는 수준까지 온 것 같은데요.",
    startFrame: 417,
    endFrame: 464
  },
  {
    text: "여러분은 어떻게 생각하시나요?",
    startFrame: 464,
    endFrame: 534
  },
  {
    text: "댓글에 생각을 공유해주시고,",
    startFrame: 534,
    endFrame: 602
  },
  {
    text: "오늘 이야기가 흥미로우셨다면 구독 한번 부탁드립니다!",
    startFrame: 602,
    endFrame: 715
  },
];
