// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "AI한테 전쟁 시뮬레이션을 시켰습니다.",
    startFrame: 0,
    endFrame: 106
  },
  {
    text: "GPT, 클로드, 제미나이.\n가상의 국가 지도자 역할을 맡긴 거예요.",
    startFrame: 106,
    endFrame: 244
  },
  {
    text: "영토 분쟁, 자원 전쟁.\n현실에서 충분히 일어날 법한 시나리오들이에요.",
    startFrame: 244,
    endFrame: 406
  },
  {
    text: "결과가 어땠냐면요. 21번 중 20번.",
    startFrame: 406,
    endFrame: 511
  },
  {
    text: "95%에서 핵무기를 선택했습니다. 협상도 아니고,\n외교도 아니고.",
    startFrame: 511,
    endFrame: 670
  },
  {
    text: "핵 버튼이에요. 올해 2월, 영국 킹스칼리지 런던\n연구팀이 이 결과를 발표하면서 이렇게 말했어요.",
    startFrame: 670,
    endFrame: 874
  },
  {
    text: "\"핵무기에 대한 금기는 인간 사회에서만큼 AI에겐\n작동하지 않는다.\"",
    startFrame: 874,
    endFrame: 1019
  },
  {
    text: "왜냐면 AI는 두렵지 않으니까요. 사람은 핵전쟁이\n어떤 건지 역사로, 감정으로, 몸으로 알아요.",
    startFrame: 1019,
    endFrame: 1217
  },
  {
    text: "근데 AI한테는 그냥 \"목표 달성에 가장 효율적인\n옵션\"인 거예요.",
    startFrame: 1217,
    endFrame: 1349
  },
  {
    text: "도덕적 고뇌 없이, 망설임 없이.\n최적화의 결과로 핵을 선택하는 겁니다.",
    startFrame: 1349,
    endFrame: 1501
  },
  {
    text: "상당히 무섭죠.\n근데 이게 그냥 실험실 얘기가 아니에요.",
    startFrame: 1501,
    endFrame: 1618
  },
  {
    text: "실제 전쟁에서도 AI가 이미 쓰이고 있다는 거,\n알고 계셨나요?",
    startFrame: 1618,
    endFrame: 1738
  },
  {
    text: "올해 초, 미국이 이란을 공격했어요.",
    startFrame: 1738,
    endFrame: 1828
  },
  {
    text: "작전 시작 첫 24시간 안에 1,000개가 넘는\n표적이 타격됐고, 이후 하루 300~500개 표적을",
    startFrame: 1828,
    endFrame: 1997
  },
  {
    text: "타격하는 속도로 이어졌어요. 이렇게 빠른 타격\n작전의 중심에는 AI가 있었습니다.",
    startFrame: 1997,
    endFrame: 2158
  },
  {
    text: "미군 중부사령부 사령관은 이렇게 직접 밝혔어요.",
    startFrame: 2158,
    endFrame: 2248
  },
  {
    text: "\"우리 전투원들은 다양한 첨단 AI 도구를 활용하고\n있다.",
    startFrame: 2248,
    endFrame: 2368
  },
  {
    text: "이 시스템들은 방대한 데이터를 수 초 안에\n분석해서, 적보다 더 빠르고 스마트한 결정을 내릴 수 있게",
    startFrame: 2368,
    endFrame: 2496
  },
  {
    text: "해준다.\" 프로젝트 메이븐,\n이번 전쟁에 투입된 핵심 AI 시스템입니다.",
    startFrame: 2496,
    endFrame: 2668
  },
  {
    text: "그리고 이 AI 시스템 안에, 여러분이 아주 잘\n아는 그 이름. 클로드가 있었습니다.",
    startFrame: 2668,
    endFrame: 2818
  },
  {
    text: "그럼 프로젝트 메이븐이 대체 뭔지, 어떻게 전쟁에\n사용됐는지, 지금부터 제대로 뜯어볼게요.",
    startFrame: 2818,
    endFrame: 2998
  },
];
