// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "올해 초, 미국이 이란을 공격했습니다.",
    startFrame: 0,
    endFrame: 61
  },
  {
    text: "작전 시작 첫 24시간 안에 1,000개가 넘는 표적이",
    startFrame: 61,
    endFrame: 168
  },
  {
    text: "타격됐는데, 사실 말이 안 되는 규모의 작전이죠.",
    startFrame: 168,
    endFrame: 259
  },
  {
    text: "역시나 이 작전의 중심에는 AI가 있었습니다.",
    startFrame: 259,
    endFrame: 360
  },
  {
    text: "그리고 그 AI 시스템 안에,",
    startFrame: 360,
    endFrame: 429
  },
  {
    text: "여러분이 매일 쓰는 클로드가 있었어요.",
    startFrame: 429,
    endFrame: 494
  },
  {
    text: "오늘은 AI가 실제 전쟁에서 어떻게 사용되고 있는지,",
    startFrame: 494,
    endFrame: 611
  },
  {
    text: "어떤 위험성을 가지고 있는지 실제 사건을 통해",
    startFrame: 611,
    endFrame: 703
  },
  {
    text: "보여드릴게요. 그리고 마지막엔, GPT, GEMINI,",
    startFrame: 703,
    endFrame: 827
  },
  {
    text: "클로드에게 각각 전쟁 시뮬레이션을 시켰을 때 나온 충격적인",
    startFrame: 827,
    endFrame: 942
  },
  {
    text: "결과도 기다리고 있으니 끝까지 시청해주세요.",
    startFrame: 942,
    endFrame: 1030
  },
];
