// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "자,",
    startFrame: 0,
    endFrame: 5
  },
  {
    text: "그럼 이제 클로드가 거기서 뭘 하는 건지 한번 알아봅시다.",
    startFrame: 5,
    endFrame: 101
  },
  {
    text: "메이븐이 데이터를 끌어오면,",
    startFrame: 101,
    endFrame: 190
  },
  {
    text: "클로드가 그걸 일단 분석하고 봅니다.",
    startFrame: 190,
    endFrame: 262
  },
  {
    text: "위성 사진, 드론 영상, 레이더, 신호 정보까지.",
    startFrame: 262,
    endFrame: 397
  },
  {
    text: "160개가 넘는 정보 채널이 실시간으로 들어오고,",
    startFrame: 397,
    endFrame: 512
  },
  {
    text: "그 데이터를 보면서 클로드는 이런 걸 해요.",
    startFrame: 512,
    endFrame: 579
  },
  {
    text: "수상한 차량 한 대를 드론이 포착했다고 해볼게요.",
    startFrame: 579,
    endFrame: 700
  },
  {
    text: "클로드가 그 차량의 이동 경로를 뒤지다가,",
    startFrame: 700,
    endFrame: 786
  },
  {
    text: "어제 특정 통신 신호가 잡힌 위치랑 겹친 거에요.",
    startFrame: 786,
    endFrame: 895
  },
  {
    text: "심지어 그 근처에서 올라온 소셜미디어 게시물도 있다?",
    startFrame: 895,
    endFrame: 1040
  },
  {
    text: "이런 식으로 판단해서 표적 후보로 올려버리는겁니다.",
    startFrame: 1040,
    endFrame: 1180
  },
  {
    text: "그리고 이렇게 뽑힌 표적들에 대해서 리스트를 만들어요.",
    startFrame: 1180,
    endFrame: 1267
  },
  {
    text: "GPS 좌표, 추천 무기,",
    startFrame: 1267,
    endFrame: 1314
  },
  {
    text: "그리고 심지어 법적 정당화 문서까지 자동으로요.",
    startFrame: 1314,
    endFrame: 1437
  },
  {
    text: "분석관이 말로 \"이 지역 위협 요소 요약해줘\" 하면,",
    startFrame: 1437,
    endFrame: 1533
  },
  {
    text: "바로 전술 브리핑을 뽑아줘요.",
    startFrame: 1533,
    endFrame: 1602
  },
  {
    text: "전쟁터에서 AI한테 말로 보고서를 받는 겁니다.",
    startFrame: 1602,
    endFrame: 1716
  },
  {
    text: "그래도 아직 마지막 결정은 사람이 내리고 AI는 그 직전",
    startFrame: 1716,
    endFrame: 1853
  },
  {
    text: "단계까지만 관여한다고 합니다.",
    startFrame: 1853,
    endFrame: 1912
  },
  {
    text: "과거 전쟁에서는 이 작업에 분석관 2,000명이",
    startFrame: 1912,
    endFrame: 2026
  },
  {
    text: "필요했는데, 지금은 겨우 20명이에요.",
    startFrame: 2026,
    endFrame: 2114
  },
  {
    text: "AI 덕분에 효율이 100배 뻥튀기 된거죠.",
    startFrame: 2114,
    endFrame: 2207
  },
];
