// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "이 작업들을 진행하는 속도가 어느 정도냐면요.",
    startFrame: 0,
    endFrame: 78
  },
  {
    text: "1시간에 최대 80개의 표적을 포착할 수 있게\n됐다고 합니다.",
    startFrame: 78,
    endFrame: 185
  },
  {
    text: "사람이 하루 종일 붙잡고 하나씩 확인할 걸,\nAI는 한 시간에 80개를 처리하는 거예요.",
    startFrame: 185,
    endFrame: 381
  },
  {
    text: "속도가 전쟁의 성격 자체를 바꿔버린 겁니다.",
    startFrame: 381,
    endFrame: 487
  },
  {
    text: "그럼 자연스럽게 드는 질문이 있죠.\n빠른 건 알겠는데. 그만큼 정확하기도 한 걸까요?",
    startFrame: 487,
    endFrame: 697
  },
  {
    text: "중동 사막 환경에서 실험했을 때예요.",
    startFrame: 697,
    endFrame: 772
  },
  {
    text: "사람은 84% 확률로 맞는 판단을 했어요.\n메이븐은요? 60%였어요.",
    startFrame: 772,
    endFrame: 972
  },
  {
    text: "AI는 트럭이랑 나무를 혼동했고,\n계곡이랑 장갑차를 혼동했습니다.",
    startFrame: 972,
    endFrame: 1109
  },
  {
    text: "사람 눈엔 당연히 다른데,\nAI한테는 \"비슷하게 생긴 물체\"인 거예요.",
    startFrame: 1109,
    endFrame: 1253
  },
  {
    text: "군 관계자도 인정했어요. \"메이븐의 장점은\n어디까지나 속도다. 전술적 판단 수준엔 아직 못 미친다.\"",
    startFrame: 1253,
    endFrame: 1493
  },
  {
    text: "그 40%의 오판이 전쟁터에서 어떤 의미인지,\n실제로 드러난 사건이 있어요.",
    startFrame: 1493,
    endFrame: 1655
  },
  {
    text: "이란 전쟁 첫날, 미군 토마호크 미사일이 이란\n남부의 한 여자 초등학교를 타격했어요.",
    startFrame: 1655,
    endFrame: 1846
  },
  {
    text: "165명 이상이 사망했고 대부분이 어린\n학생들이었어요.",
    startFrame: 1846,
    endFrame: 1955
  },
  {
    text: "미 군 예비 조사 결과, 이 타격이 오래된 정보에\n기반했을 가능성이 높은 것으로 나타났어요.",
    startFrame: 1955,
    endFrame: 2130
  },
  {
    text: "메이븐이 이 타격에 관여했는지는 아직 조사\n중이라고 하지만, 만약에라도 AI가 이 사건에 개입했다면",
    startFrame: 2130,
    endFrame: 2323
  },
  {
    text: "분명히 문제가 있는거죠.",
    startFrame: 2323,
    endFrame: 2362
  },
];
