// AUTO-GENERATED by scripts/update-gallery.py — 직접 수정하지 마세요.
import React from 'react';
import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring } from 'remotion';
import { CleanShape } from '../body1/components/CleanShape';
import { ConcentrationIcon } from '../body1/components/ConcentrationIcon';
import { GearSystem } from '../body1/components/GearSystem';
import { PomodoroTimer } from '../body1/components/PomodoroTimer';
import { RestIcon } from '../body1/components/RestIcon';
import { SortedData } from '../body1/components/SortedData';
import { TangledLines } from '../body1/components/TangledLines';
import { HandDrawnClock } from '../intro/components/HandDrawnClock';
import { HandDrawnDots } from '../intro/components/HandDrawnDots';
import { HandDrawnNotionTemplate } from '../intro/components/HandDrawnNotionTemplate';
import { HandDrawnTool } from '../intro/components/HandDrawnTool';
import { Star } from '../outro/components/Scene1Components';
import { Clock } from '../outro/components/Scene2Components';
import { LinkIcon } from '../outro/components/Scene3Components';
import { Heart } from '../outro/components/Scene4Components';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const SECTIONS: Record<string, Array<{ label: string; element: (props: any) => React.ReactNode }>> = {
  'body1': [
  {
    label: 'CleanShape',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = CleanShape as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'ConcentrationIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = ConcentrationIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'GearSystem',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = GearSystem as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'PomodoroTimer',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = PomodoroTimer as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'RestIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = RestIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'SortedData',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = SortedData as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'TangledLines',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = TangledLines as any;
      return <Comp {...props} />;
    }
  },
  ],
  'intro': [
  {
    label: 'HandDrawnClock',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = HandDrawnClock as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'HandDrawnDots',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = HandDrawnDots as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'HandDrawnNotionTemplate',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = HandDrawnNotionTemplate as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'HandDrawnTool',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = HandDrawnTool as any;
      return <Comp {...props} />;
    }
  },
  ],
  'outro': [
  {
    label: 'Star',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Star as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Clock',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Clock as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'LinkIcon',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = LinkIcon as any;
      return <Comp {...props} />;
    }
  },
  {
    label: 'Heart',
    element: (props) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const Comp = Heart as any;
      return <Comp {...props} />;
    }
  },
  ],
};

class ErrorBoundary extends React.Component<{children: React.ReactNode}, {hasError: boolean, error: Error | null}> {
  constructor(props: {children: React.ReactNode}) {
    super(props);
    this.state = { hasError: false, error: null };
  }
  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error };
  }
  render() {
    if (this.state.hasError) {
      return (
        <div style={{ color: '#D32F2F', textAlign: 'center', padding: 20 }}>
          <h3 style={{ margin: '0 0 8px 0', fontSize: 16 }}>Rendering Error</h3>
          <pre style={{ fontSize: 11, whiteSpace: 'pre-wrap', wordBreak: 'break-all', margin: 0 }}>{this.state.error?.message}</pre>
        </div>
      );
    }
    return this.props.children;
  }
}

const CARD_H = 600;
const LABEL_H = 36;

export const ComponentGallery: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  // 160프레임 주기로 반복되는 루프 (0->1->0 핑퐁)
  const loopFrame = frame % 160;
  const enter = spring({ frame: loopFrame - 20, fps, config: { damping: 14, stiffness: 120 } });
  const exit = spring({ frame: loopFrame - 140, fps, config: { damping: 14, stiffness: 120 } });
  const progress = enter - exit;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const renderGrid = (title: string, items: Array<{ label: string; element: (props: any) => React.ReactNode }>) => (
    <div style={{ padding: '40px' }} key={title}>
      <h2 style={{ fontFamily: 'sans-serif', fontSize: 32, marginBottom: 20 }}>{title} ({items.length})</h2>
      {items.length === 0 ? (
        <div style={{ color: '#BBB', fontFamily: 'monospace', fontSize: 20 }}>해당 폴더에 컴포넌트가 없습니다.</div>
      ) : (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '20px',
        }}>
          {items.map(({ label, element }) => (
            <div
              key={label}
              style={{
                height: CARD_H,
                boxSizing: 'border-box',
                border: '1px solid #DDD',
                background: '#FFF',
                display: 'flex',
                flexDirection: 'column',
                overflow: 'hidden',
                borderRadius: 12,
                boxShadow: '0 4px 12px rgba(0,0,0,0.05)'
              }}
            >
              <div style={{
                height: LABEL_H,
                padding: '0 16px',
                lineHeight: `${LABEL_H}px`,
                fontFamily: 'monospace',
                fontSize: 16,
                fontWeight: 'bold',
                color: '#555',
                borderBottom: '1px solid #EEE',
                background: '#FAFAFA',
              }}>
                {label}
              </div>
              <div style={{
                flex: 1,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                padding: 16,
                position: 'relative',
                overflow: 'auto',
              }}>
                <ErrorBoundary>
                  {element({ progress, strikeProgress: progress, revealClaude: progress })}
                </ErrorBoundary>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <AbsoluteFill style={{ background: '#F5F0EB', overflowY: 'auto' }}>
      {Object.entries(SECTIONS).map(([sectionName, items]) => 
        renderGrid(`📁 ${sectionName.toUpperCase()} 컴포넌트`, items)
      )}
    </AbsoluteFill>
  );
};
