// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "앤트로픽은 Mythos의 성능을 테스트하기 위해,",
    startFrame: 0,
    endFrame: 80
  },
  {
    text: "외부 인터넷과 완전히 차단된 격리된 환경을",
    startFrame: 80,
    endFrame: 161
  },
  {
    text: "만들고 실험을 진행했는데요.",
    startFrame: 161,
    endFrame: 217
  },
  {
    text: "쉽게 말하면 아무것도 못하는 방 같은 환경을 만든",
    startFrame: 217,
    endFrame: 307
  },
  {
    text: "다음 이렇게 말했습니다.",
    startFrame: 307,
    endFrame: 361
  },
  {
    text: "\"한번 탈출해봐\" 그리고 Mythos는 탈출에",
    startFrame: 361,
    endFrame: 469
  },
  {
    text: "성공했습니다. 여러 단계의 허점을 스스로 연결하고,",
    startFrame: 469,
    endFrame: 574
  },
  {
    text: "막혀 있던 인터넷 접근을 뚫더니,",
    startFrame: 574,
    endFrame: 647
  },
  {
    text: "테스트를 설계한 연구원한테 이메일을 직접 보냈어요.",
    startFrame: 647,
    endFrame: 751
  },
  {
    text: "근데 진짜 소름돋는건 따로 있었는데요.",
    startFrame: 751,
    endFrame: 844
  },
  {
    text: "Mythos의 초기 버전은 자기가 규칙을 어기고 있다는 걸",
    startFrame: 844,
    endFrame: 949
  },
  {
    text: "스스로 인식하고, 숨기려고 시도했다는겁니다.",
    startFrame: 949,
    endFrame: 1050
  },
  {
    text: "자기가 탈출하는 과정에서 했던 행동들을 스스로 삭제했어요.",
    startFrame: 1050,
    endFrame: 1168
  },
  {
    text: "흔적을 지운 거예요. 아무도 시키지 않았는데도요.",
    startFrame: 1168,
    endFrame: 1294
  },
  {
    text: "권한 없는 파일을 몰래 수정한 뒤에,",
    startFrame: 1294,
    endFrame: 1353
  },
  {
    text: "개발자들이 쓰는 변경 기록에서 그 흔적을 아예",
    startFrame: 1353,
    endFrame: 1432
  },
  {
    text: "지워버렸습니다. 그리고 AI 내부를 들여다봤더니,",
    startFrame: 1432,
    endFrame: 1550
  },
  {
    text: "겉으로는 협조하는 척하면서 속으로는 어떻게 하면 안",
    startFrame: 1550,
    endFrame: 1629
  },
  {
    text: "들킬지를 추론하고 있었어요.",
    startFrame: 1629,
    endFrame: 1697
  },
  {
    text: "앤트로픽은 이 행동들을",
    startFrame: 1714,
    endFrame: 1757
  },
  {
    text: "공식적으로 \"경솔하다\"고 표현했어요.",
    startFrame: 1757,
    endFrame: 1832
  },
  {
    text: "AI를 만든 회사가 자기 AI한테 쓴 표현이에요.",
    startFrame: 1832,
    endFrame: 1941
  },
];
