"""
update-gallery.py {project_id}

컴포넌트 Gallery 통합 스크립트.
  - Gallery가 없으면 생성 + Root.tsx에 Composition 등록 (init 역할)
  - components/svg/ 경로의 컴포넌트와 components/ui/ 경로의 컴포넌트를
    자동으로 읽어들여 갤러리 뷰어를 최신화합니다.
"""

import sys
import os
import re

GALLERY_WIDTH = 1920
GALLERY_HEIGHT = 1080

GALLERY_TEMPLATE = """\
// AUTO-GENERATED by scripts/update-gallery.py — 직접 수정하지 마세요.
import React from 'react';
import { AbsoluteFill } from 'remotion';
__IMPORTS__

const SVG_ITEMS: Array<{ label: string; element: () => React.ReactNode }> = [
__SVG_ITEMS__];

const UI_ITEMS: Array<{ label: string; element: () => React.ReactNode }> = [
__UI_ITEMS__];

const CARD_H = 600;
const LABEL_H = 36;

export const ComponentGallery: React.FC = () => {
  const renderGrid = (title: string, items: typeof SVG_ITEMS) => (
    <div style={{ padding: '40px' }}>
      <h2 style={{ fontFamily: 'sans-serif', fontSize: 32, marginBottom: 20 }}>{title} ({items.length})</h2>
      {items.length === 0 ? (
        <div style={{ color: '#BBB', fontFamily: 'monospace', fontSize: 20 }}>해당 폴더에 컴포넌트가 없습니다.</div>
      ) : (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '20px',
        }}>
          {items.map(({ label, element }) => (
            <div
              key={label}
              style={{
                height: CARD_H,
                boxSizing: 'border-box',
                border: '1px solid #DDD',
                background: '#FFF',
                display: 'flex',
                flexDirection: 'column',
                overflow: 'hidden',
                borderRadius: 12,
                boxShadow: '0 4px 12px rgba(0,0,0,0.05)'
              }}
            >
              <div style={{
                height: LABEL_H,
                padding: '0 16px',
                lineHeight: `${LABEL_H}px`,
                fontFamily: 'monospace',
                fontSize: 16,
                fontWeight: 'bold',
                color: '#555',
                borderBottom: '1px solid #EEE',
                background: '#FAFAFA',
              }}>
                {label}
              </div>
              <div style={{
                flex: 1,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                padding: 16,
                position: 'relative',
                overflow: 'auto',
              }}>
                {element()}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <AbsoluteFill style={{ background: '#F5F0EB', overflowY: 'auto' }}>
      {renderGrid("🎨 SVG 그림 컴포넌트 (components/svg/)", SVG_ITEMS)}
      {renderGrid("🧩 일반 UI 컴포넌트 (components/ui/)", UI_ITEMS)}
    </AbsoluteFill>
  );
};
"""

EXPORT_NAME = re.compile(r'export\s+const\s+(\w+)\s*[=:]')
ROOT_ANCHOR = re.compile(r'(\s*<></>\s*</Folder>)', re.MULTILINE)

def scan_components_in_folder(base_dir: str, subfolder: str) -> list[dict]:
    """해당 서브폴더(ui 또는 svg)내의 모든 .tsx 파싱하여 수출(export)된 컴포넌트 명 수집"""
    target_dir = os.path.join(base_dir, subfolder)
    results = []
    
    if not os.path.isdir(target_dir):
        return results

    for fname in sorted(os.listdir(target_dir)):
        if not fname.endswith('.tsx') or fname.startswith('index'):
            continue
            
        fpath = os.path.join(target_dir, fname)
        with open(fpath, 'r', encoding='utf-8') as f:
            source = f.read()

        name_match = EXPORT_NAME.search(source)
        if name_match:
            component_name = name_match.group(1)
            results.append({
                'name': component_name,
                'path': f"./{subfolder}/{fname.replace('.tsx', '')}",
            })
            print(f"  ✓ {subfolder}/{fname} → <{component_name} />")
            
    return results

def generate_gallery(svg_components: list[dict], ui_components: list[dict]) -> str:
    all_components = svg_components + ui_components
    imports_lines = [
        f"import {{ {c['name']} }} from '{c['path']}';"
        for c in all_components
    ]

    def make_items(comps):
        lines = []
        for c in comps:
            lines.append(f"  {{ label: '{c['name']}', element: () => {{ /* @ts-ignore */ return <{c['name']} />; }} }},")
        return lines

    result = GALLERY_TEMPLATE
    result = result.replace('__IMPORTS__', '\n'.join(imports_lines))
    result = result.replace('__SVG_ITEMS__', '\n'.join(make_items(svg_components)))
    result = result.replace('__UI_ITEMS__', '\n'.join(make_items(ui_components)))
    return result

def ensure_root_registered(project_id: str) -> None:
    root_path = os.path.join("src", "Root.tsx")

    if not os.path.exists(root_path):
        print(f"❌ Root.tsx 없음: {root_path}")
        return

    with open(root_path, "r", encoding="utf-8") as f:
        content = f.read()

    gallery_id = f"{project_id}-component-gallery"
    if gallery_id in content:
        return

    import_line = f"import {{ ComponentGallery }} from './projects/{project_id}/components/ComponentGallery';"
    still_block = (
        f'\n        <Composition\n'
        f'          id="{gallery_id}"\n'
        f'          component={{ComponentGallery}}\n'
        f'          width={{{GALLERY_WIDTH}}}\n'
        f'          height={{{GALLERY_HEIGHT}}}\n'
        f'          durationInFrames={{300}}\n'
        f'          fps={{30}}\n'
        f'        />'
    )

    last_import_match = list(re.finditer(r'^import .+;$', content, re.MULTILINE))
    if last_import_match:
        pos = last_import_match[-1].end()
        content = content[:pos] + "\n" + import_line + content[pos:]
    else:
        content = import_line + "\n" + content

    if not ROOT_ANCHOR.search(content):
        print("❌ Root.tsx에 삽입 앵커(<></>)를 찾지 못했습니다. 수동 등록 필요.")
        return

    content = ROOT_ANCHOR.sub(
        lambda m: still_block + m.group(0),
        content,
        count=1,
    )

    with open(root_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✅ Root.tsx에 Gallery Composition 등록 완료: {gallery_id}")

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/update-gallery.py <project_id>")
        sys.exit(1)

    project_id = sys.argv[1]
    components_dir = os.path.join("src", "projects", project_id, "components")
    gallery_path = os.path.join(components_dir, "ComponentGallery.tsx")

    print(f"\n🎨 Gallery 업데이트: {project_id}\n")

    svg_dir = os.path.join(components_dir, "svg")
    ui_dir = os.path.join(components_dir, "ui")
    os.makedirs(svg_dir, exist_ok=True)
    os.makedirs(ui_dir, exist_ok=True)

    ensure_root_registered(project_id)

    print(f"스캔: {svg_dir}")
    svg_comps = scan_components_in_folder(components_dir, "svg")
    print(f"스캔: {ui_dir}")
    ui_comps = scan_components_in_folder(components_dir, "ui")

    gallery_code = generate_gallery(svg_comps, ui_comps)
    with open(gallery_path, 'w', encoding='utf-8') as f:
        f.write(gallery_code)

    print(f"\n✅ ComponentGallery.tsx 생성 완료 (SVG: {len(svg_comps)}개, UI: {len(ui_comps)}개)")
    print(f"\n→ Remotion Studio: http://localhost:3000")
    print(f"→ Composition: {project_id}-component-gallery\n")

if __name__ == "__main__":
    main()
