"""
update-gallery.py {project_id}

컴포넌트 Gallery 통합 스크립트.
  - Gallery가 없으면 생성 + Root.tsx에 Composition 등록 (init 역할)
  - components/svg/ 경로의 컴포넌트와 components/ui/ 경로의 컴포넌트를
    자동으로 읽어들여 갤러리 뷰어를 최신화합니다.
"""

import sys
import os
import re
from typing import List, Dict, Any

GALLERY_WIDTH = 1920
GALLERY_HEIGHT = 1080

GALLERY_TEMPLATE = """\
// AUTO-GENERATED by scripts/update-gallery.py — 직접 수정하지 마세요.
import React from 'react';
import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring } from 'remotion';
__IMPORTS__

const SECTIONS: Record<string, Array<{ label: string; element: (props: any) => React.ReactNode }>> = {
__SECTION_DATA__
};

class ErrorBoundary extends React.Component<{children: React.ReactNode}, {hasError: boolean, error: Error | null}> {
  constructor(props: {children: React.ReactNode}) {
    super(props);
    this.state = { hasError: false, error: null };
  }
  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error };
  }
  render() {
    if (this.state.hasError) {
      return (
        <div style={{ color: '#D32F2F', textAlign: 'center', padding: 20 }}>
          <h3 style={{ margin: '0 0 8px 0', fontSize: 16 }}>Rendering Error</h3>
          <pre style={{ fontSize: 11, whiteSpace: 'pre-wrap', wordBreak: 'break-all', margin: 0 }}>{this.state.error?.message}</pre>
        </div>
      );
    }
    return this.props.children;
  }
}

const CARD_H = 600;
const LABEL_H = 36;

export const ComponentGallery: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  // 160프레임 주기로 반복되는 루프 (0->1->0 핑퐁)
  const loopFrame = frame % 160;
  const enter = spring({ frame: loopFrame - 20, fps, config: { damping: 14, stiffness: 120 } });
  const exit = spring({ frame: loopFrame - 140, fps, config: { damping: 14, stiffness: 120 } });
  const progress = enter - exit;

  const renderGrid = (title: string, items: Array<{ label: string; element: (props: any) => React.ReactNode }>) => (
    <div style={{ padding: '40px' }} key={title}>
      <h2 style={{ fontFamily: 'sans-serif', fontSize: 32, marginBottom: 20 }}>{title} ({items.length})</h2>
      {items.length === 0 ? (
        <div style={{ color: '#BBB', fontFamily: 'monospace', fontSize: 20 }}>해당 폴더에 컴포넌트가 없습니다.</div>
      ) : (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '20px',
        }}>
          {items.map(({ label, element }) => (
            <div
              key={label}
              style={{
                height: CARD_H,
                boxSizing: 'border-box',
                border: '1px solid #DDD',
                background: '#FFF',
                display: 'flex',
                flexDirection: 'column',
                overflow: 'hidden',
                borderRadius: 12,
                boxShadow: '0 4px 12px rgba(0,0,0,0.05)'
              }}
            >
              <div style={{
                height: LABEL_H,
                padding: '0 16px',
                lineHeight: `${LABEL_H}px`,
                fontFamily: 'monospace',
                fontSize: 16,
                fontWeight: 'bold',
                color: '#555',
                borderBottom: '1px solid #EEE',
                background: '#FAFAFA',
              }}>
                {label}
              </div>
              <div style={{
                flex: 1,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                padding: 16,
                position: 'relative',
                overflow: 'auto',
              }}>
                <ErrorBoundary>
                  {element({ progress, strikeProgress: progress, revealClaude: progress })}
                </ErrorBoundary>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <AbsoluteFill style={{ background: '#F5F0EB', overflowY: 'auto' }}>
      {Object.entries(SECTIONS).map(([sectionName, items]) => 
        renderGrid(`📁 ${sectionName.toUpperCase()} 컴포넌트`, items)
      )}
    </AbsoluteFill>
  );
};
"""

EXPORT_NAME = re.compile(r'export\s+const\s+(\w+)\s*[=:]')
ROOT_ANCHOR = re.compile(r'(\s*<></>\s*</Folder>)', re.MULTILINE)

def scan_components_in_folder(target_dir: str, section_name: str) -> list[dict]:
    """해당 섹션 폴더(components) 내의 모든 .tsx 파싱하여 수출(export)된 컴포넌트 명 수집"""
    results = []
    
    if not os.path.isdir(target_dir):
        return results

    for fname in sorted(os.listdir(target_dir)):
        if not fname.endswith('.tsx') or fname.startswith('index'):
            continue
            
        fpath = os.path.join(target_dir, fname)
        with open(fpath, 'r', encoding='utf-8') as f:
            source = f.read()

        name_match = EXPORT_NAME.search(source)
        if name_match:
            component_name = name_match.group(1)
            results.append({
                'name': component_name,
                'path': f"../{section_name}/components/{fname.replace('.tsx', '')}",
            })
            print(f"  ✓ {section_name}/components/{fname} → <{component_name} />")
            
    return results

def generate_gallery(sections: Dict[str, List[Dict[str, Any]]]) -> str:
    all_components = []
    for comps in sections.values():
        all_components.extend(comps)
        
    imports_lines = [
        f"import {{ {c['name']} }} from '{c['path']}';"
        for c in all_components
    ]

    def make_items(comps):
        lines = []
        for c in comps:
            lines.append(
                f"  {{\n"
                f"    label: '{c['name']}',\n"
                f"    element: (props) => {{\n"
                f"      // eslint-disable-next-line @typescript-eslint/no-explicit-any\n"
                f"      const Comp = {c['name']} as any;\n"
                f"      return <Comp {{...props}} />;\n"
                f"    }}\n"
                f"  }},"
            )
        return lines

    result = GALLERY_TEMPLATE

    section_data_lines: List[str] = []
    for section_name, comps in sections.items():
        section_data_lines.append(f"  '{section_name}': [")
        section_data_lines.extend(make_items(comps))
        section_data_lines.append("  ],")
        
    result = result.replace('__IMPORTS__', '\n'.join(imports_lines))
    result = result.replace('__SECTION_DATA__', '\n'.join(section_data_lines))
    return result

def ensure_root_registered(project_id: str) -> None:
    root_path = os.path.join("src", "Root.tsx")

    if not os.path.exists(root_path):
        print(f"❌ Root.tsx 없음: {root_path}")
        return

    with open(root_path, "r", encoding="utf-8") as f:
        content: str = str(f.read())

    gallery_id = f"{project_id}-component-gallery"
    if gallery_id in content:
        return

    import_line = f"import {{ ComponentGallery }} from './projects/{project_id}/components/ComponentGallery';"
    still_block = (
        f'\n        <Composition\n'
        f'          id="{gallery_id}"\n'
        f'          component={{ComponentGallery}}\n'
        f'          width={{{GALLERY_WIDTH}}}\n'
        f'          height={{{GALLERY_HEIGHT}}}\n'
        f'          durationInFrames={{300}}\n'
        f'          fps={{30}}\n'
        f'        />'
    )

    last_import_match = list(re.finditer(r'^import .+;$', content, re.MULTILINE))
    if last_import_match:
        pos: int = last_import_match[-1].end()
        # pyre-ignore[16]: Pyre2 internal bug with str slicing
        content = str(content[:pos]) + "\n" + import_line + str(content[pos:])
    else:
        content = import_line + "\n" + content

    if not ROOT_ANCHOR.search(content):
        print("❌ Root.tsx에 삽입 앵커(<></>)를 찾지 못했습니다. 수동 등록 필요.")
        return

    content = ROOT_ANCHOR.sub(
        lambda m: still_block + m.group(0),
        content,
        count=1,
    )

    with open(root_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✅ Root.tsx에 Gallery Composition 등록 완료: {gallery_id}")

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/update-gallery.py <project_id>")
        sys.exit(1)

    project_id = sys.argv[1]
    project_dir = os.path.join("src", "projects", project_id)
    components_dir = os.path.join(project_dir, "components")
    os.makedirs(components_dir, exist_ok=True)
    gallery_path = os.path.join(components_dir, "ComponentGallery.tsx")

    print(f"\n🎨 Gallery 업데이트: {project_id}\n")

    ensure_root_registered(project_id)

    sections: Dict[str, List[Dict[str, Any]]] = {}
    total_comps: int = 0
    
    # 스캔: 프로젝트 폴더 내의 각 섹션 (intro, body1, ...)
    for item in sorted(os.listdir(project_dir)):
        section_dir = os.path.join(project_dir, item)
        if os.path.isdir(section_dir) and item not in ['components', 'images']:
            components_dir = os.path.join(section_dir, "components")
            if os.path.isdir(components_dir):
                print(f"스캔: {item}/components")
                comps = scan_components_in_folder(components_dir, item)
                if comps:
                    sections[item] = comps
                    # pyre-ignore[58]: Pyre2 internal bug with augmented assignment
                    total_comps += len(comps)

    gallery_code = generate_gallery(sections)
    with open(gallery_path, 'w', encoding='utf-8') as f:
        f.write(gallery_code)

    print(f"\n✅ ComponentGallery.tsx 생성 완료 (총 {total_comps}개)")
    print(f"\n→ Remotion Studio: http://localhost:3000")
    print(f"→ Composition: {project_id}-component-gallery\n")

if __name__ == "__main__":
    main()
