"""
update-gallery.py {project_id}

컴포넌트 Gallery 통합 스크립트.
  - Gallery가 없으면 생성 + Root.tsx에 Still 등록 (init 역할)
  - Gallery가 있으면 컴포넌트 재스캔 후 재생성 (update 역할)

컨벤션:
  각 컴포넌트 파일에 아래 주석을 추가하면 Gallery에 자동 등록됩니다:
    // @gallery: <ComponentName progress={1} color="#E8A87C" />
  이 주석이 없으면 해당 컴포넌트는 Gallery에서 제외됩니다.
"""

import sys
import os
import re

GALLERY_WIDTH = 1920
GALLERY_HEIGHT = 1080

# __IMPORTS__, __ITEMS__, __WIDTH__ 를 str.replace로 치환
GALLERY_TEMPLATE = """\
// AUTO-GENERATED by scripts/update-gallery.py — 직접 수정하지 마세요.
// 컴포넌트에 `// @gallery: <Component ... />` 주석을 추가하고 스크립트를 재실행하세요.
import React from 'react';
import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring } from 'remotion';
__IMPORTS__

const GALLERY_ITEMS: Array<{ label: string; element: (p: number) => React.ReactNode }> = [
__ITEMS__];

const CARD_H = 320;
const LABEL_H = 36;

export const ComponentGallery: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  
  // Create a ping-pong progress from 0 to 1 over 60 frames
  const loopDuration = 60;
  const cycle = Math.floor(frame / loopDuration);
  const cycleFrame = frame % loopDuration;
  const rawP = cycleFrame / loopDuration;
  
  // Eased progress (ping-pong)
  const p = cycle % 2 === 0 
    ? 1 - Math.pow(1 - rawP, 3) 
    : Math.pow(1 - rawP, 3);

  return (
    <AbsoluteFill
      style={{
        background: '#F5F0EB',
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        alignContent: 'start',
        overflowY: 'auto',
      }}
    >
      {GALLERY_ITEMS.length === 0 && (
        <div style={{ margin: 'auto', color: '#BBB', fontFamily: 'monospace', fontSize: 28 }}>
          Gallery is empty — add @gallery comments to components
        </div>
      )}
      {GALLERY_ITEMS.map(({ label, element }) => (
        <div
          key={label}
          style={{
            height: CARD_H,
            boxSizing: 'border-box',
            border: '1px solid #DDD',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
          }}
        >
          <div style={{
            height: LABEL_H,
            padding: '0 12px',
            lineHeight: `${LABEL_H}px`,
            fontFamily: 'monospace',
            fontSize: 18,
            color: '#888',
            borderBottom: '1px solid #EEE',
            background: '#FFF',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            position: 'relative',
            zIndex: 10,
          }}>
            {label}
          </div>
          <div style={{
            flex: 1,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 16,
            position: 'relative',
            overflow: 'hidden',
          }}>
            {element(p)}
          </div>
        </div>
      ))}
    </AbsoluteFill>
  );
};
"""

# @gallery 주석 패턴
GALLERY_ANNOTATION = re.compile(r'//\s*@gallery:\s*(.+)')

# export const ComponentName 패턴
EXPORT_NAME = re.compile(r'export\s+const\s+(\w+)\s*[=:]')

# Root.tsx 앵커: <></> (빈 fragment) 바로 앞
ROOT_ANCHOR = re.compile(r'(\s*<></>\s*</Folder>)', re.MULTILINE)


def scan_components(components_dir: str) -> list[dict]:
    """@gallery 주석이 있는 컴포넌트를 스캔"""
    results = []
    skip = {'ComponentGallery.tsx', 'index.ts', 'index.tsx'}

    if not os.path.isdir(components_dir):
        return results

    for fname in sorted(os.listdir(components_dir)):
        if fname in skip or not fname.endswith('.tsx'):
            continue

        fpath = os.path.join(components_dir, fname)
        with open(fpath, 'r', encoding='utf-8') as f:
            source = f.read()

        annotation = GALLERY_ANNOTATION.search(source)
        if not annotation:
            continue

        jsx_preview = annotation.group(1).strip()

        name_match = EXPORT_NAME.search(source)
        component_name = name_match.group(1) if name_match else fname.replace('.tsx', '')

        results.append({
            'name': component_name,
            'file': fname.replace('.tsx', ''),
            'jsx_preview': jsx_preview,
        })
        print(f"  ✓ {fname} → {jsx_preview[:60]}{'...' if len(jsx_preview) > 60 else ''}")

    return results


def generate_gallery(components: list[dict]) -> str:
    imports_lines = [
        f"import {{ {c['name']} }} from './{c['file']}';"
        for c in components
    ]
    items_lines = []
    for c in components:
        jsx_str = c['jsx_preview']
        # Replace hardcoded progress={1} or progress={0} with progress={p}
        jsx_preview_with_p = re.sub(r'progress=\{[0-9.]+\}', 'progress={p}', jsx_str)
        items_lines.append(f"  {{ label: '{c['name']}', element: (p: number) => {jsx_preview_with_p} }},")

    result = GALLERY_TEMPLATE
    result = result.replace('__IMPORTS__', '\n'.join(imports_lines))
    result = result.replace('__ITEMS__', '\n'.join(items_lines) + ('\n' if items_lines else ''))
    result = result.replace('__WIDTH__', str(GALLERY_WIDTH))
    return result


def ensure_root_registered(project_id: str) -> None:
    """Root.tsx에 Gallery Still이 없으면 등록"""
    root_path = os.path.join("src", "Root.tsx")

    if not os.path.exists(root_path):
        print(f"❌ Root.tsx 없음: {root_path}")
        return

    with open(root_path, "r", encoding="utf-8") as f:
        content = f.read()

    gallery_id = f"{project_id}-component-gallery"
    if gallery_id in content:
        return  # 이미 등록됨

    import_line = f"import {{ ComponentGallery }} from './projects/{project_id}/components/ComponentGallery';"
    still_block = (
        f'\n        <Composition\n'
        f'          id="{gallery_id}"\n'
        f'          component={{ComponentGallery}}\n'
        f'          width={{{GALLERY_WIDTH}}}\n'
        f'          height={{{GALLERY_HEIGHT}}}\n'
        f'          durationInFrames={{300}}\n'
        f'          fps={{30}}\n'
        f'        />'
    )

    # import 삽입
    last_import_match = list(re.finditer(r'^import .+;$', content, re.MULTILINE))
    if last_import_match:
        pos = last_import_match[-1].end()
        content = content[:pos] + "\n" + import_line + content[pos:]
    else:
        content = import_line + "\n" + content

    # Still 블록 삽입
    if not ROOT_ANCHOR.search(content):
        print("❌ Root.tsx에 삽입 앵커(<></>)를 찾지 못했습니다. 수동 등록 필요.")
        return

    content = ROOT_ANCHOR.sub(
        lambda m: still_block + m.group(0),
        content,
        count=1,
    )

    with open(root_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✅ Root.tsx에 Gallery Still 등록 완료: {gallery_id}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/update-gallery.py <project_id>")
        sys.exit(1)

    project_id = sys.argv[1]
    components_dir = os.path.join("src", "projects", project_id, "components")
    gallery_path = os.path.join(components_dir, "ComponentGallery.tsx")

    print(f"\n🎨 Gallery 업데이트: {project_id}\n")

    # 디렉토리 없으면 생성
    os.makedirs(components_dir, exist_ok=True)

    # Root.tsx 등록 확인
    ensure_root_registered(project_id)

    # 컴포넌트 스캔
    print(f"스캔: {components_dir}")
    components = scan_components(components_dir)

    # Gallery 생성/재생성
    gallery_code = generate_gallery(components)
    with open(gallery_path, 'w', encoding='utf-8') as f:
        f.write(gallery_code)

    print(f"\n✅ ComponentGallery.tsx {'재생성' if components else '초기화'} 완료 ({len(components)}개 컴포넌트)")
    print(f"\n→ Remotion Studio: http://localhost:3000")
    print(f"→ Still: {project_id}-component-gallery\n")


if __name__ == "__main__":
    main()
