// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "메이븐이 하는 일을 한 줄로 요약하면 이래요.",
    startFrame: 0,
    endFrame: 74
  },
  {
    text: "\"드론이 찍어오는 걸 AI가 실시간으로 보고,\n위험한 것만 골라낸다.\"",
    startFrame: 74,
    endFrame: 227
  },
  {
    text: "드론이 찍은 영상이 하루 24시간, 전 세계에서\n실시간으로 쏟아져 들어오면, 사람이 전부 볼 수가",
    startFrame: 227,
    endFrame: 435
  },
  {
    text: "없어요. \"이거 군사 차량이야, 민간 차량이야?\",\n\"저 건물에 뭐가 있는 거야?\"",
    startFrame: 435,
    endFrame: 612
  },
  {
    text: "하루 종일 화면만 들여다봐도 감당이 안 돼요.",
    startFrame: 612,
    endFrame: 705
  },
  {
    text: "그래서 AI가 대신 보기 시작한 겁니다.",
    startFrame: 705,
    endFrame: 797
  },
  {
    text: "메이븐이 하는 일은 크게 세 단계예요.",
    startFrame: 797,
    endFrame: 894
  },
  {
    text: "첫 번째, 사물을 식별해요. 드론 영상, 위성\n사진, 열감지 레이더까지 전부 끌어모아서 분석해요.",
    startFrame: 894,
    endFrame: 1150
  },
  {
    text: "\"저 물체 탱크야, 트럭이야?\",\n\"저 건물에서 사람 움직임이 감지되는데?\"",
    startFrame: 1150,
    endFrame: 1319
  },
  {
    text: "이걸 1초도 안 걸려서 판단해요. 두 번째,\n표적을 추적해요.",
    startFrame: 1319,
    endFrame: 1471
  },
  {
    text: "영상 하나만 보는 게 아니에요.",
    startFrame: 1471,
    endFrame: 1521
  },
  {
    text: "IP 주소, 소셜미디어 위치 태그, GPS 기록,\n통신 패턴까지 전부 끌어와서 교차 분석합니다.",
    startFrame: 1521,
    endFrame: 1740
  },
  {
    text: "예를 들면 이런 거예요.\n드론이 수상한 차량 한 대를 포착했어요.",
    startFrame: 1740,
    endFrame: 1891
  },
  {
    text: "AI가 그 차량의 이동 경로를 추적하다 보니,\n어제 특정 통신 신호가 잡힌 위치랑 겹쳐요.",
    startFrame: 1891,
    endFrame: 2090
  },
  {
    text: "그런데 심지어 그 통신 신호 근처에서 올라온\n소셜미디어 게시물도 있네?",
    startFrame: 2090,
    endFrame: 2240
  },
  {
    text: "이런 식으로 표적인지 아닌지를 판단할 수\n있는거에요.",
    startFrame: 2240,
    endFrame: 2320
  },
  {
    text: "세 번째, 우선순위를 뽑아요.",
    startFrame: 2338,
    endFrame: 2426
  },
  {
    text: "\"이 건물, 무기 시설일 확률 98%입니다.\",\n\"이 차량, 군사 지휘 차량으로 추정됩니다.\"",
    startFrame: 2426,
    endFrame: 2646
  },
  {
    text: "이렇게 리스트를 만들어서 사람한테 올리는 거예요.",
    startFrame: 2646,
    endFrame: 2752
  },
];
