// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "우선 이 작전의 중심에 있던 시스템,",
    startFrame: 0,
    endFrame: 74
  },
  {
    text: "프로젝트 메이븐에 대해 알아봐야합니다.",
    startFrame: 74,
    endFrame: 113
  },
  {
    text: "메이븐을 이해하기 위해 2017년으로 한번 돌아가",
    startFrame: 113,
    endFrame: 231
  },
  {
    text: "보자구요. 당시 미국 국방부가 심각한 고민에 빠졌어요.",
    startFrame: 231,
    endFrame: 356
  },
  {
    text: "전 세계에 깔린 군사 드론이 하루 24시간 영상을",
    startFrame: 356,
    endFrame: 459
  },
  {
    text: "찍어서 막 쏟아붓는데,",
    startFrame: 459,
    endFrame: 508
  },
  {
    text: "그걸 어떻게 사람이 일일히 다 보고 있겠어요.",
    startFrame: 508,
    endFrame: 585
  },
  {
    text: "\"저게 군사 차량이야, 민간 차량이야?\"",
    startFrame: 585,
    endFrame: 685
  },
  {
    text: "이러다가 전쟁이 먼저 끝나는 거죠.",
    startFrame: 685,
    endFrame: 749
  },
  {
    text: "그래서 만든 게 메이븐이에요. Bloomberg 기자이자,",
    startFrame: 749,
    endFrame: 866
  },
  {
    text: "메이븐을 수년간 취재한 카트리나 맨슨은 이 시스템을 이렇게",
    startFrame: 866,
    endFrame: 971
  },
  {
    text: "표현했어요. \"전쟁판 구글 어스예요.",
    startFrame: 971,
    endFrame: 1064
  },
  {
    text: "고도, 좌표, 그 위치에 뭐가 있는지,",
    startFrame: 1064,
    endFrame: 1140
  },
  {
    text: "아군인지 적군인지. 이 모든 정보가 담긴 전쟁 지도예요.\"",
    startFrame: 1140,
    endFrame: 1260
  },
  {
    text: "처음에 드론 영상 분석 도구로 시작한 메이븐은,",
    startFrame: 1260,
    endFrame: 1364
  },
  {
    text: "8년이 지난 지금 전쟁 전체를",
    startFrame: 1364,
    endFrame: 1415
  },
  {
    text: "운영하는 시스템으로 커졌습니다.",
    startFrame: 1415,
    endFrame: 1478
  },
  {
    text: "그리고 클로드가 이 시스템의 핵심",
    startFrame: 1478,
    endFrame: 1542
  },
  {
    text: "기능을 수행하고 있는거에요.",
    startFrame: 1542,
    endFrame: 1582
  },
];
