// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "그렇다면 얼마나 능력이 뛰어나길래 위험하다고 판단했을까요?",
    startFrame: 0,
    endFrame: 108
  },
  {
    text: "세상에는 \"제로데이 취약점\"이라는게 있습니다.",
    startFrame: 108,
    endFrame: 220
  },
  {
    text: "아직 공개되지 않은, 아무도 모르는 보안 허점인데요,",
    startFrame: 220,
    endFrame: 339
  },
  {
    text: "Mythos는 이런 취약점을 대량으로 찾아내고 공격할 수",
    startFrame: 339,
    endFrame: 453
  },
  {
    text: "있을 정도의 뛰어난 모습을 보였습니다.",
    startFrame: 453,
    endFrame: 515
  },
  {
    text: "대표적인 사례가 있는데,",
    startFrame: 515,
    endFrame: 578
  },
  {
    text: "보안이 뛰어나다고 알려진 한 운영체제에서,",
    startFrame: 578,
    endFrame: 665
  },
  {
    text: "27년간 아무도 발견하지 못했던",
    startFrame: 665,
    endFrame: 723
  },
  {
    text: "버그를 하루만에 찾아냈습니다.",
    startFrame: 723,
    endFrame: 784
  },
  {
    text: "즉 비전문가도 딸깍 한번으로 시스템을 해킹할 수 있는",
    startFrame: 803,
    endFrame: 894
  },
  {
    text: "능력을 갖게된다는 거에요.",
    startFrame: 894,
    endFrame: 948
  },
  {
    text: "이런 AI를 세상에 공개한다면 전세계의 시스템이 공격받게",
    startFrame: 948,
    endFrame: 1064
  },
  {
    text: "될 가능성이 있는거죠.",
    startFrame: 1064,
    endFrame: 1099
  },
];
