// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "자, 일단 AI를 쓰는건 알겠는데,",
    startFrame: 0,
    endFrame: 66
  },
  {
    text: "과연 이 AI를 어디까지 믿을 수 있을까요?",
    startFrame: 66,
    endFrame: 155
  },
  {
    text: "한번 테스트를 해봤습니다.",
    startFrame: 155,
    endFrame: 221
  },
  {
    text: "메이븐의 정확도는 어느정도일까요? 약 60%예요.",
    startFrame: 221,
    endFrame: 352
  },
  {
    text: "사람이 분석했을 때는 같은 조건에서",
    startFrame: 352,
    endFrame: 435
  },
  {
    text: "84%고요. 생각보다는 정확하다고요?",
    startFrame: 435,
    endFrame: 527
  },
  {
    text: "이 얘기를 듣고도 그렇게 생각할 수는 없을 겁니다.",
    startFrame: 527,
    endFrame: 629
  },
  {
    text: "그 날은 이란 전쟁이 시작된 첫날,",
    startFrame: 629,
    endFrame: 721
  },
  {
    text: "2월 28일 아침이었습니다.",
    startFrame: 721,
    endFrame: 793
  },
  {
    text: "이란 남부 미납이라는 도시의 한 초등학교 앞,",
    startFrame: 793,
    endFrame: 887
  },
  {
    text: "학부모들이 평소처럼 아이들을 학교에",
    startFrame: 887,
    endFrame: 958
  },
  {
    text: "데려다주고 있을 때였어요.",
    startFrame: 958,
    endFrame: 1008
  },
  {
    text: "갑자기 미군 토마호크 미사일이 그 학교를 타격했습니다.",
    startFrame: 1008,
    endFrame: 1124
  },
  {
    text: "이 공격으로 168명이 사망했는데,",
    startFrame: 1124,
    endFrame: 1228
  },
  {
    text: "대부분이 7살에서 12살 사이의 아이들이었어요.",
    startFrame: 1228,
    endFrame: 1331
  },
  {
    text: "왜 이런 비극같은 일이 생겼을까요.",
    startFrame: 1331,
    endFrame: 1399
  },
  {
    text: "그 학교 바로 옆에 이란 혁명수비대 시설이 있었어요.",
    startFrame: 1399,
    endFrame: 1504
  },
  {
    text: "근데 2013년에서 2016년 사이에 담장이 하나",
    startFrame: 1504,
    endFrame: 1606
  },
  {
    text: "세워지면서, 학교와 군사 시설이 분리됐거든요.",
    startFrame: 1606,
    endFrame: 1686
  },
  {
    text: "미군 예비 조사 결과,",
    startFrame: 1686,
    endFrame: 1758
  },
  {
    text: "이 타격이 오래된 정보에 기반했을 가능성이",
    startFrame: 1758,
    endFrame: 1846
  },
  {
    text: "높은 것으로 나타났어요.",
    startFrame: 1846,
    endFrame: 1886
  },
  {
    text: "AI가 이 타격에 관여했는지는 지금도 조사 중이라 명확히",
    startFrame: 1886,
    endFrame: 2003
  },
  {
    text: "밝혀진 것은 아니지만,",
    startFrame: 2003,
    endFrame: 2044
  },
  {
    text: "솔직히 사람이 직접 판단해서 초등학교를 공격했을까요?",
    startFrame: 2044,
    endFrame: 2153
  },
  {
    text: "개인적으로는 AI가 개입했을 확률이",
    startFrame: 2153,
    endFrame: 2227
  },
  {
    text: "상당히 높다고 생각합니다.",
    startFrame: 2227,
    endFrame: 2287
  },
  {
    text: "하원 의원 120명 이상이 국방부 장관에게 서한을 보낸",
    startFrame: 2287,
    endFrame: 2392
  },
  {
    text: "상태예요. \"AI가 그 학교를 표적으로 선정했습니까?\"",
    startFrame: 2392,
    endFrame: 2505
  },
  {
    text: "60%짜리 AI가 전쟁터에서 어떤 의미인지.",
    startFrame: 2505,
    endFrame: 2633
  },
  {
    text: "충분히 이해하셨을 겁니다. 그리고 사실,",
    startFrame: 2633,
    endFrame: 2718
  },
  {
    text: "이보다 더 근본적인 문제가 있어요.",
    startFrame: 2718,
    endFrame: 2786
  },
  {
    text: "AI를 일부러 틀리게 만들 수도 있습니다.",
    startFrame: 2786,
    endFrame: 2865
  },
  {
    text: "메이븐은 학습 데이터에 의존해요.",
    startFrame: 2865,
    endFrame: 2932
  },
  {
    text: "그 데이터가 오염되면, AI 판단 자체가 오염돼요.",
    startFrame: 2932,
    endFrame: 3028
  },
  {
    text: "만약 적대국이 그 데이터에 슬쩍 오류를",
    startFrame: 3028,
    endFrame: 3101
  },
  {
    text: "심어놓으면 어떻게 될까요.",
    startFrame: 3101,
    endFrame: 3152
  },
  {
    text: "AI가 민간 시설을 군사 시설로 추천할 수도 있게 됩니다.",
    startFrame: 3152,
    endFrame: 3259
  },
  {
    text: "이게 새로운 형태의 전쟁이에요.",
    startFrame: 3259,
    endFrame: 3315
  },
];
