// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "원래 클로드의 다음 모델로 mythos가 출시될 것이라",
    startFrame: 0,
    endFrame: 85
  },
  {
    text: "많은 사람들이 생각했지만,",
    startFrame: 85,
    endFrame: 126
  },
  {
    text: "4월 16일에 출시된",
    startFrame: 126,
    endFrame: 167
  },
  {
    text: "것은 다름아닌 opus4.7이었습니다.",
    startFrame: 167,
    endFrame: 254
  },
  {
    text: "앤트로픽이 공식적으로 한 말이 있는데,",
    startFrame: 254,
    endFrame: 342
  },
  {
    text: "opus4.7의 보안 관련 성능은 mythos보다 덜",
    startFrame: 359,
    endFrame: 426
  },
  {
    text: "강력하다고 합니다. 현재 mythos의 보안 능력은,",
    startFrame: 426,
    endFrame: 553
  },
  {
    text: "아마존, 애플, 구글,",
    startFrame: 553,
    endFrame: 595
  },
  {
    text: "마이크로소프트 같은 빅테크들에만 비공개로 제공하는 대신,",
    startFrame: 595,
    endFrame: 711
  },
  {
    text: "방어 목적으로만 쓰게 하도록 제한되어 있습니다.",
    startFrame: 711,
    endFrame: 790
  },
  {
    text: "그렇다고 opus4.7의 성능이 나쁘냐 하면,",
    startFrame: 817,
    endFrame: 896
  },
  {
    text: "그건 또 아닙니다.",
    startFrame: 896,
    endFrame: 931
  },
  {
    text: "코딩 실력에 대해서는 지금 공개된 AI 중에",
    startFrame: 931,
    endFrame: 1013
  },
  {
    text: "1등이라고 평가받고 있습니다.",
    startFrame: 1013,
    endFrame: 1085
  },
  {
    text: "법률 문서 처리나 복잡한 분석 같은 전문직 영역에서도",
    startFrame: 1085,
    endFrame: 1192
  },
  {
    text: "최상위 수준이라고 하고요. 따라서 보안,",
    startFrame: 1192,
    endFrame: 1280
  },
  {
    text: "해킹 관련 직무가 아닌 이상 성능이 낮게",
    startFrame: 1280,
    endFrame: 1352
  },
  {
    text: "느낄 이유는 없는거죠.",
    startFrame: 1352,
    endFrame: 1385
  },
];
