// Auto-generated by scripts/generate-captions.py
export const captions = [
  {
    text: "머릿속 복잡한 생각들을 정리하는 것만으로도",
    startFrame: 0,
    endFrame: 80
  },
  {
    text: "뇌의 부하가 줄어들죠.",
    startFrame: 80,
    endFrame: 118
  },
  {
    text: "두 번째는 집중력을 극대화하는",
    startFrame: 118,
    endFrame: 189
  },
  {
    text: "'뽀모도로 타이머' 활용법이에요.",
    startFrame: 189,
    endFrame: 263
  },
  {
    text: "딱 25분만 몰입하고 5분 쉬는 규칙이 업무 속도를",
    startFrame: 263,
    endFrame: 377
  },
  {
    text: "두 배로 만듭니다.",
    startFrame: 377,
    endFrame: 419
  },
  {
    text: "마지막 세 번째는 반복되는 단순 노동을 대신해 주는",
    startFrame: 419,
    endFrame: 546
  },
  {
    text: "AI 자동화 툴입니다.",
    startFrame: 546,
    endFrame: 599
  },
];
